### ISSUE TITLE
Some platform for communication

### ISSUE THREAD

**Issue by LDprg** [winapps-org/winapps#1]
We should probably have some sort of chat for discussions, because Github issues are not great for that purpose.

I would suggest discord server if nobody has something against it.

**Comment by Sithuk** [comment]
You can enable a discussions area on GitHub.

**Comment by freechelmi** [comment]
I won't be opposed to discord but i feel it is usually overkill and complexe 

I feel that Telegram channel is more efficient but require a mobile phone number to join AFAIK

**Comment by oskardotglobal** [comment]
Discussions will probably suffice

**Comment by LDprg** [comment]
I enabled Github discussions.
