### ISSUE TITLE
installer.sh: line 140: grep -l -d skip: command not found

### ISSUE THREAD

**Issue by Alchemi1963** [winapps-org/winapps#110]
Quite simply the title to be honest.
I tried fixing this but couldn't find how since I don't entirely understand how !/usr/bin/env bash works.

Yes, I do have grep installed and I'm able to invoke it on my own.

>  Would you like to install for the current user or the whole system? User
> Removing any old configurations...
>   Removing /home/melody/.local/share/applications/excel-o365.desktop... Finished.
>   Removing /home/melody/.local/share/applications/explorer.desktop... Finished.
>   Removing /home/melody/.local/share/applications/powerpoint-o365.desktop... Finished.
>   Removing /home/melody/.local/share/applications/windows.desktop... Finished.
>   Removing /home/melody/.local/share/applications/word-o365.desktop... Finished.
>   Removing /home/melody/.local/bin/excel-o365... Finished.
>   Removing /home/melody/.local/bin/explorer... Finished.
>   Removing /home/melody/.local/bin/powerpoint-o365... Finished.
>   Removing /home/melody/.local/bin/windows... Finished.
>   Removing /home/melody/.local/bin/word-o365... Finished.
> Installing...
>   Checking for installed apps in RDP machine (this may take a while)... Finished.
>   Configuring Windows... Finished.
> installer.sh: line 140: grep -l -d skip: command not found
> ? How would you like to handle WinApps pre-configured applications? If any web browser is set-up, may be configured as default browser. (Use arrow keys)
> ❯ Set up all detected pre-configured applications 
>   Select which pre-configured applications to set up
>   Do not set up any pre-configured applications

**Comment by oskardotglobal** [comment]
What OS are you running? It might be due to not running GNU grep?

**Comment by jrevillard** [comment]
I have the same on ubuntu 24.04

**Comment by oskardotglobal** [comment]
I feel like the fix mentioned in https://github.com/winapps-org/winapps/pull/108#discussion_r1632237661 might fix this

**Comment by LDprg** [comment]
@jrevillard @Alchemi1963 is this fixed with #139?

**Comment by KernelGhost** [comment]
@LDprg IIRC, I independently identified and corrected this issue in that PR.

**Comment by KernelGhost** [comment]
This issue should be able to be closed now. @Alchemi1963, would this be alright with you?
