### ISSUE TITLE
Downloading Tiny 11 from cnxiaobai is extremely slow

### ISSUE THREAD

**Issue by Minksh** [winapps-org/winapps#120]
I don't know if its just me, but the download for the tiny11 image is very slow. I'm talking like 40kb/s max.
Not sure if this is due to my docker configuration, but I haven't throttled download speeds anywhere. Could anyone confirm?

**Comment by NaeemBolchhi** [comment]
I can confirm the slow speed. I was at 4% after 4 hours or so. It then tried downloading from archive.org, only marginally faster. I ended up downloading the tiny11 iso from archive.org manually and marking that to be used locally. I recommend doing the same.

**Comment by LDprg** [comment]
This is something we cannot do much about.

But you could try to open an issue [here](https://github.com/dockur/windows).

**Comment by Minksh** [comment]
> I can confirm the slow speed. I was at 4% after 4 hours or so. It then tried downloading from archive.org, only marginally faster. I ended up downloading the tiny11 iso from archive.org manually and marking that to be used locally. I recommend doing the same.



> I can confirm the slow speed. I was at 4% after 4 hours or so. It then tried downloading from archive.org, only marginally faster. I ended up downloading the tiny11 iso from archive.org manually and marking that to be used locally. I recommend doing the same.



> I can confirm the slow speed. I was at 4% after 4 hours or so. It then tried downloading from archive.org, only marginally faster. I ended up downloading the tiny11 iso from archive.org manually and marking that to be used locally. I recommend doing the same.



> This is something we cannot do much about.
> 
> But you could try to open an issue [here](https://github.com/dockur/windows).



> This is something we cannot do much about.
> 
> But you could try to open an issue [here](https://github.com/dockur/windows).



> This is something we cannot do much about.
> 
> But you could try to open an issue [here](https://github.com/dockur/windows).

Thank you for the responses, at least I know its not my docker configuration.
