### ISSUE TITLE
RDPWindows is not running

### ISSUE THREAD

**Issue by timur-g** [winapps-org/winapps#129]
This is a spin off from https://github.com/winapps-org/winapps/issues/95

Everything was working for me with KVM in Linux Mint 21.3 based on Ubuntu 22.04.
I `git pull` today and got `You are not a member of the libvirt group` and added again.
I checked `~/.config/libvirt/libvirt.conf` empty and added `uri_default = "qemu:///system"`.
But still NOK.
```
 virsh list 
 Id   Name         State
----------------------------
 1    RDPWindows   running

bin/winapps check       
RDPWindows is not running, run:
  virsh start RDPWindows

virsh start RDPWindows            
error: Domain is already active 
```
Previously when all was working,  `~/.config/winapps/winapps.conf` did not have IP. 
If I add `RDP_IP="127.0.0.1"` then I see freerdp errors, for which I assume I would have to install freerdp3 but that is not available in Mint repo.

Is there a way to `git checkout` before all changes, so that tit is working again as it did? I tried, but failed.

**Comment by timur-g** [comment]
NOK with 16d5d8d875f9051dfe1a8068cd203dbd5f25fb14, OK with 152a92412badea5e366c918be1cebd142624e377.

I would like to keep this open to have working updated installation with KVM and FreeRDP2, without additional settings.

**Comment by oskardotglobal** [comment]
FreeRDP2 and virt-manager are deprecated.
