### ISSUE TITLE
Dialogs moved on open

### ISSUE THREAD

**Issue by timur-g** [winapps-org/winapps#132]
My conf is libvirt as seen in #129.
I installed Collabora Office (based on LibreOffice), both are freely available. 
When opening a dialog like Tools-Options, or popup like Help-Tip of the day, every other time the dialog moves to the right (after it is open centered, as it should).
Does not happen in VB, so I assume this is something about WinApps handling of dialogs, but could not find.

**Comment by KernelGhost** [comment]
@timur-g I've encountered a similar issue where the sign-in popup windows for Microsoft applications, such as Microsoft Teams, initially open in the centre of the screen but then drift towards the right. This behaviour is almost certainly a bug within `FreeRDP`.

**Comment by oskardotglobal** [comment]
We cannot fix FreeRDP issues.
