### ISSUE TITLE
Windows is downloading way too slowly

### ISSUE THREAD

**Issue by undeflnedCat** [winapps-org/winapps#134]
Windows downloads extremely slowly as seen on this picture (30 minutes of downloading)
![Downloading Tiny 11 from cnxiaobai.com (1.5%) (after 30 minutes)](https://github.com/user-attachments/assets/0b6c333f-0c73-4eee-8252-0a341957b8b1)

Is there a way to use an existing ISO file?

**Comment by undeflnedCat** [comment]
It now downloads from archive.org, still curious of a way to use an existing ISO file.

![Downloading Tiny 11 from archive.org (41.8%)](https://github.com/user-attachments/assets/62b79b9b-34da-447a-a972-a6ba6034e621)

**Comment by MrTumnis** [comment]
The website that is used to fetch Tiny11 is incredibly bloated, and is it is likely a Chinese website, so it will cause significant throttle depending on where you are. You could use the Tin11 builder and create your own iso file, or you could even use UnattendedWinstall.

**Comment by LDprg** [comment]
Please report this to [docker windows](https://github.com/dockur/windows). The download of the tiny11 image is part of their docker files, maybe they could provide a faster mirror.

**Comment by KernelGhost** [comment]
Please refer to [this conversation](https://github.com/dockur/windows/issues/629) on the `dockur/windows` repository.
