### ISSUE TITLE
Continuous "ERROR: VM NOT RUNNING." and status 1 errors

### ISSUE THREAD

**Issue by posumundi** [winapps-org/winapps#141]
Installed Kubuntu today, assuming its the same ver as the newest Ubuntu (24.02), on  Surface 3. 

Used Docker to (manually) set up Windows 10 and made a local account to be used with with winapps. When I run the installer or bin/winapps check however, it keeps returning either a Status 1 error (installer) or tells me that my VM isnt running when it definitely is (check). When I enter virsh list, my VM doesnt appear, only with docker ps. I have added `export LIBVIRT_DEFAULT_URI="qemu:///system"` to both my .profile and .bash_profile files and rebooted, still not working. Ive used both "localhost" and "127.0.0.1" as IP in the winapps.config, both dont change anything. 

my config:
`RDP_USER="user"

RDP_PASS="password"

#RDP_DOMAIN="MYDOMAIN"

#RDP_IP="localhost"

#RDP_SCALE=100

#RDP_FLAGS=""

#MULTIMON="true"

#DEBUG="true"

#FREERDP_COMMAND="xfreerdp"`

my .yaml:
`name: "winapps"

volumes:
  data:

services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      MANUAL: "Y"
      VERSION: "tiny10"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      environment:
    privileged: true
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    volumes:
      - data:/storage
      - /home/useri/Downloads/Win10_22H2_German_x64v1.iso:/custom.iso`

Im so sorry for the formatting. Its getting late and I dont really get how this works, first time github poster. Mainly wanted to switch to Linux bc Windows is forcing win11 unto me and I thought winapps was my solution for my university needs.

**Comment by LDprg** [comment]
@posumundi you will need to uncomment the RDP_IP line in order to take effect.

**Comment by KernelGhost** [comment]
This is a bug introduced on my behalf as of yesterday. I will begin correcting this ASAP.

**Comment by posumundi** [comment]
okay wow, thank you. I feel kinda stupid now for having missed the hashtag. Thank you for telling me!!

Word is working now, which was my main concern. Since my screen resolution is 3kx2k Word ends up looking real small and my cursor is mirror for some reasons (lol?) but I can most likely fix that myself by playing around with settings in the config or otherwise. If not, I can live with it too. Again, thank you so much for both continuing development on this and helping me out. :-)

**Comment by KernelGhost** [comment]
@posumundi With regards to your display scaling issue, have you looked into modifying 'RDP_SCALE' within `~/.config/winapps/winapps.conf`?
