### ISSUE TITLE
No freerdp detected

### ISSUE THREAD

**Issue by SunilPaul174** [winapps-org/winapps#143]
![Screenshot_20240717_100703](https://github.com/user-attachments/assets/b9084a30-64b7-4057-ba95-eedf4641ff5b)
I have installed freerdp from the freerdp-git AUR packaged and the install script does not detect it

**Comment by KernelGhost** [comment]
What command is used to run FreeRDP on your system?

**Comment by SunilPaul174** [comment]
![image](https://github.com/user-attachments/assets/a18f4ce1-c588-423b-97ca-47a35bfda3b1)
No, it's `xfreerdp`. No clue what's going on here

**Comment by KernelGhost** [comment]
Can you please provide the complete output of the following command on your system?

```bash
xfreerdp --version
```

**Comment by SunilPaul174** [comment]
`❯ xfreerdp --version
This is FreeRDP version 3.6.4-dev0 (1033471a3)
Keyboard Shortcuts:
        <Right CTRL>
                releases keyboard and mouse grab
        <CTRL>+<ALT>+<Return>
                toggles fullscreen state of the application
        <CTRL>+<ALT>+c
                toggles remote control in a remote assistance session
        Action Script
                Executes a predefined script on key press.
                Should the script not exist it is ignored.
                Scripts can be provided at the default location ~/.config/freerdp/action.sh or as command line argument /action:script:<path>
                The script will receive the current key combination as argument.
                The output of the script is parsed for 'key-local' which tells that the script used the key combination, otherwise the combination is forwarded to the remote.`

**Comment by KernelGhost** [comment]
I believe I have identified the problem and will get back to you shortly.
