### ISSUE TITLE
Winapps doesn't see Win11 in docker

### ISSUE THREAD

**Issue by arrogantworm** [winapps-org/winapps#145]
Hello!
I'm pretty new to all this, and can't figure out, what may be the problem.
I'm running fedora.
I installed docker. Using standard compose.yaml installed tiny 11, it is running, I can see it in browser and via docker ps.
But installer.sh keep raising this error
`Checking the status of the Windows VM... Exiting with status '1'.`

Config file:

```
RDP_USER="Docker"
RDP_PASS="pass123"
#RDP_DOMAIN="MYDOMAIN"
RDP_IP="localhost"
RDP_SCALE=200
#RDP_FLAGS=""
#MULTIMON="true"
#DEBUG="true"
FREERDP_COMMAND="xfreerdp"
```

I tried localhost, 127.0.0.1 for RDP_IP
and commenting it out

**Comment by KernelGhost** [comment]
@arrogantworm The bug you are experiencing is a result of one of the pull requests that I submitted that was merged recently. I have submitted a follow-up PR to correct this.

In the mean time, you may be able to bypass this bug by commenting out the calls to the functions `waCheckGroupMembership`, `waCheckVMRunning` and `waCheckVMContactable` in the function `waInstall` in `installer.sh`.

Similarly, comment out calls to the functions `waCheckGroupMembership`, `waCheckVMRunning` and `waCheckVMContactable` in `bin/winapps`.

Let me know how you go.

**Comment by arrogantworm** [comment]
@KernelGhost 
Thank you, I just copied 2 files from your fix and it's working now!
Now I'm stuck on 
```
ERROR: REMOTE DESKTOP PROTOCOL FAILURE.
FreeRDP failed to establish a connection with the Windows VM 'RDPWindows'.
```
But I hope I'll figure it out :D

**Comment by KernelGhost** [comment]
I'll begin looking into your second issue now. If you do identify the problem, please let me know so I can add it to the open pull request. Thanks!

**Comment by arrogantworm** [comment]
From logs:
`[14:21:26:640] [24577:00006001] [ERROR][com.freerdp.client.common.cmdline] - [freerdp_client_settings_parse_command_line_arguments_int]: Command line parsing failed at 'scale' value '200' [-1002]
`

**Comment by KernelGhost** [comment]
I am able to reproduce this issue by setting `RDP_SCALE=200` in my `winapps.conf`, thank you for sharing your logs.

**Comment by KernelGhost** [comment]
I was able to fix this issue via the following changes:
1. Add the following function to `installer.sh`.
    ```bash
    # Name: 'waFixScale'
    # Role: Since FreeRDP only supports '/scale' values of 100, 140 or 180, find the closest supported argument to the user's configuration.
    function waFixScale() {
        # Define variables.
        local USER_CONFIG_SCALE="$1"
        local CLOSEST_SCALE=100
        local VALID_SCALE_1=100
        local VALID_SCALE_2=140
        local VALID_SCALE_3=180
    
        # Calculate the absolute differences.
        local DIFF_1=$(( USER_CONFIG_SCALE > VALID_SCALE_1 ? USER_CONFIG_SCALE - VALID_SCALE_1 : VALID_SCALE_1 - USER_CONFIG_SCALE ))
        local DIFF_2=$(( USER_CONFIG_SCALE > VALID_SCALE_2 ? USER_CONFIG_SCALE - VALID_SCALE_2 : VALID_SCALE_2 - USER_CONFIG_SCALE ))
        local DIFF_3=$(( USER_CONFIG_SCALE > VALID_SCALE_3 ? USER_CONFIG_SCALE - VALID_SCALE_3 : VALID_SCALE_3 - USER_CONFIG_SCALE ))
    
        # Set the final scale to the valid scale value with the smallest absolute difference.
        if (( DIFF_1 <= DIFF_2 && DIFF_1 <= DIFF_3 )); then
            CLOSEST_SCALE="$VALID_SCALE_1"
        elif (( DIFF_2 <= DIFF_1 && DIFF_2 <= DIFF_3 )); then
            CLOSEST_SCALE="$VALID_SCALE_2"
        else
            CLOSEST_SCALE="$VALID_SCALE_3"
        fi
    
        # Return the final scale value.
        echo "$CLOSEST_SCALE"
    }
    ```

2. Add the following to `waInstall` in `installer.sh`.
    ```bash
    # Update $RDP_SCALE.
    RDP_SCALE=$(waFixScale "$RDP_SCALE")
    ```

**Comment by arrogantworm** [comment]
Worked great with 180

**Comment by KernelGhost** [comment]
@arrogantworm Great to hear we were able to resolve the problem :)
