### ISSUE TITLE
Outdated `kvm/RDPWindows.xml`

### ISSUE THREAD

**Issue by KernelGhost** [winapps-org/winapps#152]
The `.xml` file provided at `kvm/RDPWindows.xml` is outdated and no longer matches `docs/libvirt.md`. An example `.xml` snippet is already provided in the documentation. Is there any value to keeping this file within the repository?

**Comment by LDprg** [comment]
I think we could safely remove it, since virsh isn't directly supported anyways.

@oskardotglobal what are your thoughts?
