### ISSUE TITLE
Error Winapps Libvirt 

### ISSUE THREAD

**Issue by Rosnerv** [winapps-org/winapps#155]
I get this error when trying to install with Libvirt:

Checking for an open RDP Port on Windows... ./installer.sh: línea 802: arp: orden no encontrada

Exiting with status '1'.

I imagine it is an error in the script programming.

**Comment by KernelGhost** [comment]
Hello @Rosnerv, thank you for your interest in the project! I apologise for the issue introduced during the installation script rewrite. I have added additional dependency checks for 'netcat' and 'arp' in PR #153. This issue should be resolved once the PR is merged.

In the meantime, depending on your GNU/Linux distribution, you could run one of the following commands:

```bash
sudo apt install net-tools #Debian/Ubuntu
sudo dnf install net-tools #Red Hat/Fedora
sudo pacman -S net-tools #Arch Linux
sudo emerge --ask sys-apps/net-tools #Gentoo Linux
```

Please let me know if this resolves the issue for you.

**Comment by KernelGhost** [comment]
@Rosnerv Can you please confirm if the issue persists after pulling the latest changes from the repository and re-attempting the WinApps installation?

**Comment by Rosnerv** [comment]
> @Rosnerv Can you please confirm if the issue persists after pulling the latest changes from the repository and re-attempting the WinApps installation?

Excellent, now it works.

Thank you so much.
