### ISSUE TITLE
Problem with running installer - Errors out at Checking the status of the WIndows VM... with status '1'

### ISSUE THREAD

**Issue by YourKalamity** [winapps-org/winapps#159]
Hello all.
I have configured a Windows 10 virtual machine as per the guide on [here](https://github.com/winapps-org/winapps/blob/main/docs/libvirt.md), installed all the virtio drivers, installed SPICE guest tools and enabled remote desktop, ensuring my VM is called RDPWindows and ensuring remote desktop is enabled.

This is on Arch Linux and my VM was created using Virt Manager

Below is my config file :
```
~/.config/winapps/winapps.conf
```
```
RDP_USER="kalam"
RDP_PASS="<my_windows_pass>"
#RDP_DOMAIN="MYDOMAIN"
#RDP_IP="localhost"
WAFLAVOR="libvirt" # Acceptable values are 'docker', 'podman' and 'libvirt'.
#RDP_SCALE=100 # Acceptable values are 100, 140, and 180.
#RDP_FLAGS=""
#MULTIMON="true"
#DEBUG="true"
#FREERDP_COMMAND="xfreerdp"
```

This is the output I get from the installer : 
![image](https://github.com/user-attachments/assets/ec40e154-8255-487b-9713-9a68fa6f7a2f)

I am unsure of where to access the logs, but please let me know if there's more information I can provide :>

**Comment by KernelGhost** [comment]
Hello Kalam,

Thank you for your interest in this project.

It appears that the script is exiting without providing any explanation because a non-zero exit code is likely being returned by line 741 in `installer.sh`. This line contains the command:

```bash
VM_STATE=$(virsh list --all | grep -w "$VM_NAME")
```
Here, `$VM_NAME` should evaluate to "RDPWindows." To debug this issue, try running the same command in your preferred shell to see what output it returns.

Please execute the following command and share the results with us:

```bash
virsh list --all | grep -w "RDPWindows"
```

**Comment by YourKalamity** [comment]
Hello and thanks for your reply.

It appears my VM does not appear in the list :
```
$ virsh list --all | grep -w "RDPWindows"
```
```
<blank_output>
```

Without the grep command
```
$ virsh list --all
```
```
 Id   Name   State
--------------------
```

I can definitely see the VM In virt manager : 
![image](https://github.com/user-attachments/assets/e81efd2d-0e0c-4171-badf-06ecaaf291c4)

**Comment by KernelGhost** [comment]
Does VMM request elevated privileges before connecting to QEMU/KVM? What is the output of `sudo virsh list --all`?

**Comment by YourKalamity** [comment]
Running with sudo displays the virtual machine
```
 Id   Name         State
----------------------------
 4    RDPWindows   running
```

However adding myself to the `libvirt` and `kvm` groups still does not show the VM when run without sudo

**Comment by LDprg** [comment]
does running winapps as sudo work?

**Comment by YourKalamity** [comment]
If possible I would not like to run it as sudo, I would like to run it under my user. The installer does go past the stage I was stuck at when I use root instead of my personal account

**Comment by LDprg** [comment]
> If possible I would not like to run it as sudo, I would like to run it under my user. The installer does go past the stage I was stuck at when I use root instead of my personal account

@YourKalamity Then you either need to run the vm as user or use podman instead. It's very likely a virsh permission problem.

I would recommend you to setup the vm with podman (like offically recommended). This works around all those strange permission errors which could happen when using libvirt.

**Comment by KernelGhost** [comment]
@YourKalamity It is possible that you are using the incorrect URI. Please run `virsh --connect qemu:///system list --all` to see if this lists your Windows virtual machine without the use of elevated privileges.

**Comment by YourKalamity** [comment]
The incorrect URI was the issue.
I had incorrectly added the line to set my `LIBVIRT_DEFAULT_URI` in `.bashrc` instead of `.zshrc` 

Thank you both for the help :>
