### ISSUE TITLE
File not found when trying to open a file in the home directory

### ISSUE THREAD

**Issue by gordoncheong** [winapps-org/winapps#162]
Hi. Absolutely love you guys' work, that's why I am trying to add support for Microsoft Visio to WinApps. On its own it works just as well as other Office programs. But when I try to open a file in my home directory with Visio setup by the installer script, it doesn't work and I got this error:

![Screenshot_20240724_232802](https://github.com/user-attachments/assets/bc86f67c-e158-470a-9dac-2d4b930a304f)

As you can see, the file definitely exists at the specified location, so I am not sure why it doesn't work. The (old) officially supported programs such as Word, PowerPoint and Excel is no problem though.

Interestingly, Access, which is also an (old) officially supported program, doesn't work either!

![image](https://github.com/user-attachments/assets/25225f91-c84b-4fa8-b931-2124b8c51c4e)

I am using WinApps on Fedora 40 KDE with a Docker Windows VM.

**Comment by gordoncheong** [comment]
I forgot to mention that saving a file from Visio to the home directory is also fine. Opening a file from the home directory through `tsclient` within Windows works too. It only fails when I try to open the file from Linux through WinApps.

**Comment by KernelGhost** [comment]
This appears to be an issue with how backslashes within the path are escaped and interpreted. I will investigate and get back to you.

**Comment by KernelGhost** [comment]
I can reproduce the issue. The log file located at `~/.local/share/winapps/winapps.log` shows the following entries:

```
[Thu 25 Jul 2024 14:27:23 AEST-14981] Using FreeRDP command 'xfreerdp'.
[Thu 25 Jul 2024 14:27:23 AEST-14981] UNIX_FILE_PATH: /home/RohanBarar/Database21.accdb
[Thu 25 Jul 2024 14:27:23 AEST-14981] WINDOWS_FILE_PATH: \\\\tsclient\\home\\Database21.accdb
[Thu 25 Jul 2024 14:27:23 AEST-14981] END
```

It seems that the logic for converting UNIX paths to Windows paths might be malfunctioning. I will continue to investigate this issue.
