### ISSUE TITLE
RDPApps.reg 404 - page not found.

### ISSUE THREAD

**Issue by PierreV23** [winapps-org/winapps#163]
https://github.com/winapps-org/winapps/blob/main/docs/libvirt.md links to https://github.com/winapps-org/winapps/blob/main/install/RDPApps.reg, which does not exist.

The file does exist in the original repo: https://github.com/Fmstrat/winapps/blob/main/install/RDPApps.reg.

1. Is this intentional?
2. Can I just use the one from Fmstrat's repo?

**Comment by KernelGhost** [comment]
The file you are looking for was moved [here](https://github.com/winapps-org/winapps/blob/main/oem/RDPApps.reg). I will update the documentation to include the updated link.
