### ISSUE TITLE
No Audio with /sound flag under WinApps, but running xrdp with /sound flag works fine

### ISSUE THREAD

**Issue by itiligent** [winapps-org/winapps#169]
I am testing on two fresh systems of LMDE6 and LM 21 Ubuntu and here is what I am observing in both:

- Manually connecting to a Windows 10 Docker guest with xrdp shows the /sound flag working ok and an audio device is also present in the Windows mmsys. cpl. 
- However if I use /sound as an RDP_FLAG, sound does not work for apps launched by WinApps and there is also no audio device available in the mmsys. cpl if I run this from a WinApps cmd prompt.

I've spent hours on this trying many things sudh as /sound:sys:alsa, then installed Pulse and tried /sound:sys:pulse. I've also tried flatpak FreeRDP and freerdp3-x11 and all give the same results. For giggles I've also tested sound from the Windows container through a Guacamole jump host which also works ok, so I'm quite comfortable there's no issue with either Windows or the Linux host it would seem.

I cant see any other issues raised on this, perhaps there is something I am missing?

**Comment by LDprg** [comment]
@itiligent  why would you want to set /sound? Winapps automatically sets /audio-mode:1 which i guess wont work combined with /sound and enables audio.

I am not sure what the goal is, since you didn't mentioned audio problems? Please clarify what problem you trying to solve.

**Comment by itiligent** [comment]
I neglected to say (but in my own mind inferred) that with the default settings of RDP_FLAGS="" (unset) in the WinApps config sound does not work and no audio devices are presented to apps launched by WinApps. (The Fmstat legacy version used to work fine with an /sound:sys:alsa setting on the same hardware)
 
I tested with the /sound flag when manually running running xrdp. This info was provided to explain the observation that in all other aspects the underlying FreeRDP3 system on the Linux host appears to be working fine.   

The goal is to simply have sounds from Windows apps such as audible alerts for upcoming meetings and all other manner of sound based inteactions we are accustomed to responding to from windows like many other RDP clients out of the box.

**Comment by acrilique** [comment]
I had to set audio-mode:0 and then I got sound working. Is there a consensus on whether we want the default to be audio on the remote (on the docker container, basically disabled in our use case from my perspective) which is what audio-mode:1 stands for, or audio-mode:0? If the general feeling is to have audio disabled by default, I'll make a PR to mention how to activate audio somewhere in the docs, or the readme, or a new md file. If not, we could change it to audio-mode:0 and also mention how to disable audio in the docs.

**Comment by itiligent** [comment]
For those looking for a soluiton to enable sound:

Adding `/audo-mode:0` into the `~/.config/winapps.conf` file under RDP_FLAGS enables sound. 

Perhaps I can suggest a halfway between default enabling and disabling in the code. 

Why not at leasr add to the documentation example of the wonapps.conf file the above flag with at least a  comment `# audio-mode:0 = sound off` or somthing self explanatory like that. These sorts of tiny changes will save people a lot of frustration without creating a great deal of extra work to document or code.

**Comment by itiligent** [comment]
Reopening because I've been a bit confused by the expected way sound is to be set vs the reality.  

I did not realise that the audio-mode:0 actually must be set in up to 4 places in the bin/winapps file.  This somewaht contradicts what can be inferred be the default setings in the readme regarding the winapps.conf file . Also the legacy winapps used the config file no problems, so I feel thats where I got lost.

May I please suggest that the current approach seems a bit counter intuitive.  Also, editing in the bin/winapps file itelf may get just be overwritten by any future git updates, so its all a bit unfriendly when the config file is right there

I'm not a noob,  but I've lost quite a few hours on this so I just thought I'd share the experience and as I'm sure others will bump into the same thing.

**Comment by itiligent** [comment]
as sound on/off if now handled by the config file, this can be closed.
