### ISSUE TITLE
Wrong time in VM, keeps resetting

### ISSUE THREAD

**Issue by eylenburg** [winapps-org/winapps#173]
I noticed that the default docker/podman VM has the wrong time, several hours in the future (!) despite being set to a US time zone while I'm in Europe. This lead to a wrong time and date in file modification dates (related to https://github.com/winapps-org/winapps/issues/133). 

So I went to the Time & Date settings in Windows, disabled "set time automatically" and manually set the correct time and date and time zone.

This fixed the time being several hours off the real time, however after each PC reboot, the time in the VM is changed to be one hour behind the real time. See this screenshot:
![image](https://github.com/user-attachments/assets/4a00439d-9a01-4644-b622-0c76d75efc9d)

I can manually change it in the VM's settings again, but after a reboot it will again show me the time one hour behind. Does any have any idea what could cause this?

It might lead to data loss if for example you're syncing your files and the modification date is used to decide which version is the newer one.

**Comment by oskardotglobal** [comment]
This is an issue with the windows docker image. Please open this issue on the dockur/windows repository.

**Comment by eylenburg** [comment]
The solution was to add a key in the Windows registry:

`reg add HKLM\SYSTEM\CurrentControlSet\Control\TimeZoneInformation /v RealTimeIsUniversal /t REG_DWORD /d 1`

**Comment by itiligent** [comment]
It seems lots of people encounter time issues containers it seems. The registry solution from @eylenburg (that is also proposed in the Windows/Dockur site) will only be effective in Docker where the container timezone is locked to UTC.

For Podman the container timezone can be set, which in some cases would make the RealTimeIsUniveral registry change not so universal after all. A more flexible workaround I've found is simply to set the timezone in Windows as needed, and then use a scheduled task to re-sync time to this zone at boot. Below is an exampe timesync script that could be added to install.bat. Login scripts would acheive the same.
 
```
:: Create timesync scheduled task'
echo set "taskname=SyncTimeAtStartup"
echo set "command=SC start W32Time & W32tm /ReSync /force"

schtasks /query /tn "%taskname%" >nul 2>&1
if %ERRORLEVEL% equ 0 (
echo Task "%taskname%" already exists, deleting it first...
schtasks /delete /tn "%taskname%" /f
)

schtasks /create /tn "%taskname%" /tr "cmd.exe /c %command%" /sc onstart /ru "SYSTEM" /rl HIGHEST /f

if %ERRORLEVEL% equ 0 (
echo Scheduled task "%taskname%" created successfully.
) else (
echo Failed to create scheduled task.
)
