### ISSUE TITLE
Winapps changes the selected keyboard

### ISSUE THREAD

**Issue by Rosnerv** [winapps-org/winapps#174]
My installation of Winapps is in Spanish, as well as the selected keyboard, however, winapps changes the keyboard, when using Excel the keyboard is in English and I have both the host and the virtual machine configured in Spanish.

This did not happen with the old version of Winapps.

Sorry for my English, I use G Translate.

Thanks.

**Comment by oskardotglobal** [comment]
This is a bug with freerdp and windows. 
See #43 and https://github.com/dockur/windows/issues/551.
