### ISSUE TITLE
Please Add support for running UWP apps 

### ISSUE THREAD

**Issue by cleanerspam** [winapps-org/winapps#183]
We can create shortcut for installed UWP apps (apps installed from Microsoft Store) by pressing WIN+R keys together to launch RUN dialog box and type `shell:appsfolder` and press Enter . It’ll open Applications folder containing list of all installed UWP apps and 3rd party software programs where right-click on the app and select Create shortcut option and create shortcut on desktop 

Now I tried it with Whatsapp Desktop (better than whatsapp web because it has calling featureand works oflline )
[WhatsApp - Shortcut.txt please rename extension to lnk ](https://github.com/user-attachments/files/16455098/WhatsApp.-.Shortcut.txt)

Now can the winapps script be modified to include shortcuts on desktop and run them ?

**Comment by cleanerspam** [comment]
Update - 
I  tried `./bin/winapps manual "C:\Users\Docker\Desktop\whatsapp"` after creating the shortcut file on desktop and renaming it to whatsapp.

![image](https://github.com/user-attachments/assets/0d561713-37e4-4e6a-8018-a5904ac7cea1)



Now it all just needs official winapps support to integrate desktop shortcuts in respective category in Linux application menu.

**Comment by KernelGhost** [comment]
Hi @cleanerspam,
Funny enough, this was also posted earlier today: https://github.com/Fmstrat/winapps/pull/129#discussion_r1698927139
I will look into this further when I have time.

**Comment by KernelGhost** [comment]
I have added UWP application support as per winapps-org/winapps#186.

**Comment by awsms** [comment]
Do UWP apps work flawlessly for everyone else? I'm able to launch any regular app, but anything UWP won't open.

**Comment by cleanerspam** [comment]
> Do UWP apps work flawlessly for everyone else? I'm able to launch any regular app, but anything UWP won't open.

Not flawlessly but they do launch after one or two attempt after first startup of host

**Comment by KernelGhost** [comment]
@awsms Please open a new issue and provide us with as much information about your particular setup. We will do our best to help figure out why UWP applications in particular are failing to launch on your system.

**Comment by awsms** [comment]
Hi @KernelGhost! Made one here, https://github.com/winapps-org/winapps/issues/266, could you let me know if there are other ways of debugging the winapps script?

**Comment by GuiFlam** [comment]
If I have ONe NOte installed from the microsoft store, how do I use it with winapps?
