### ISSUE TITLE
installation is successful but applications have no shortcuts

### ISSUE THREAD

**Issue by domenicop-1991** [winapps-org/winapps#190]
Installer.sh successfully concludes the installation but at the end it doesn't create any shortcut anywhere in my pc, is this an error? how do I call up the installed apps?

Virtual machine is fully functional and reachable in localhost

![Screenshot_20240803_195943](https://github.com/user-attachments/assets/7544d5e8-5a95-4765-88c3-000ff9506d80)

Operating System: Ubuntu 24.04 LTS                  
Kernel: Linux 6.8.0-39-generic
Architecture: x86-64

**Comment by KernelGhost** [comment]
@domenicop-1991 For a user-based installation, the application launchers are placed in `~/.local/share/applications/`. Your desktop environment should automatically detect these `.desktop` files and add them to your application list.

**Comment by domenicop-1991** [comment]
but there is no .desktop file in the folder ~/.local/share/applications/ or rather, there is only one that I entered manually

```
(base) domenico@domenico-ms7c37:~/.local/share/applications$ ls
defaults.list  mimeapps.list  splashtop-viewer.desktop  wine
```

Should I install it at the system level? would it help?

**Comment by KernelGhost** [comment]
If the `.desktop` files are not being created, there might be a problem with your directory permissions, or the directory might not exist and the installer fails to create it before attempting to write files to it.

As a debugging step, could you check if the following command runs successfully in a non-elevated shell prompt?

```bash
EXAMPLE_FILE="\
Line1
Line2
Line3"
echo "$EXAMPLE_FILE" | tee "${HOME}/.local/share/applications/example.txt"
cd ~/.local/share/applications
ls
cat example.txt
```

**Comment by domenicop-1991** [comment]
![Screenshot_20240805_015543](https://github.com/user-attachments/assets/33dd56f4-75fd-47d3-98e4-593e4f1ea560)

The command is executed correctly, the text file is created.

I also saw with ls -l ~/.local/share/applications the permissions which are as follows:

(basic) domenico@domenico-ms7c37:~$ ls -l ~/.local/share | grep "applications"
drwx------ 3 domenico domenico 4096 aug 5 01:54 applications

**Comment by KernelGhost** [comment]
@domenicop-1991 To debug the function `waConfigureApp` in `installer.sh`, I recommend the following steps:

1. Remove the `&>/dev/null` suffixes from the function.
2. Add `set -x` at the top of the script to enable debugging feedback.

These changes will allow you to run the installation with detailed debugging information, which should help identify the issue. Given the vague symptoms, it's challenging to pinpoint the exact problem without more information. Therefore, any findings you can share after making these changes would be very helpful.

Additionally, you might consider adding `echo` statements within the `waConfigureApp` function to verify that the relevant variables contain valid paths, file contents, etc.

**Comment by domenicop-1991** [comment]
Good evening, thank you for the suggestion, based on that I could tell there was a permissions problem with the virtual machine that i had created using SUDO, I gave full control permissions to my user for the affected folders, uninstalled winapps, reinstalled it from scratch and that's how it worked! thank you very much
