### ISSUE TITLE
"You need xfreerdp!", grep: no such file or directory

### ISSUE THREAD

**Issue by Ellish-idk** [winapps-org/winapps#193]
Os: Endeavour OS
![изображение](https://github.com/user-attachments/assets/7453887c-5290-450b-ab0a-70eef93b0790)
I included "You need xfreerdp!" ones because i'm not really sure what do i do because it gives me apt-get command (i have pacman) and i couldn't find package name for pacman
help

**Comment by KernelGhost** [comment]
Based on your screenshot, it looks like you are running quite an old version of the installer. Please re-clone or pull the latest changes from this repository to see if this resolves your issue.
