### ISSUE TITLE
Windows does not exist launched from Application Menu on Plasma 6.1.3

### ISSUE THREAD

**Issue by kaanchinar** [winapps-org/winapps#198]
Hello. I've opened an issue that WinApps stuck at black screen #112 . I somehow managed to fix it with `xfreerdp3` on Wayland. wl-freedrp3 and sdl-freerdp3 not worked and crashed of connection time.

But I have another issue, I cannot start apps from application menu on KDE Plasma 6.1.3. Although, from Terminal, I can start any windows e.g. `winapps explorer %F` works as expected. I installed winapps System Wide.  
Here is an example from one application .desktop file:
![Screenshot_20240806_224455](https://github.com/user-attachments/assets/059a424f-3d9d-404c-8e31-71875eee45c9)

My system information:
```
Operating System: Arch Linux 
KDE Plasma Version: 6.1.3
KDE Frameworks Version: 6.4.0
Qt Version: 6.7.2
Kernel Version: 6.10.3-zen1-1-zen (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 7600X 6-Core Processor
Memory: 14.7 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 4060/PCIe/SSE2
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7E26
System Version: 1.0

---
~ xfreerdp3 --version
This is FreeRDP version 3.6.3 (n/a)

```
Thanks for your answers.

**Comment by oskardotglobal** [comment]
Wayland is simply unsupported. See #19.

**Comment by milos7250** [comment]
Hi, I apologize for commenting on a closed issue, but I have found a quick workaround for this issue. Simply adding `export LIBVIRT_DEFAULT_URI="qemu:///system"` to the beginning of the winapps script (in `~/.local/bin/` if installed for a user) works.

**Comment by LarveyOfficial** [comment]
@milos7250 THANK YOU! This has been driving me crazy. Unsure why they keep closing it saying "Wayland is unsupported" when it has nothing to do with wayland.... I tested between X11 and Wayland, issue occurred on both. Thanks a ton!

**Comment by rushiiMachine** [comment]
BTW, if you changed the target VM name in `setup.sh` when installing, then you have to do the same with `~/.local/bin/winapps` and change `readonly VM_NAME="RDPWindows"` to match! This is what solved it for me, and I am on wayland

**Comment by AkechiShiro** [comment]
We should probably document this workaround/quickfix somewhere

**Comment by Sithuk** [comment]
> Hi, I apologize for commenting on a closed issue, but I have found a quick workaround for this issue. Simply adding `export LIBVIRT_DEFAULT_URI="qemu:///system"` to the beginning of the winapps script (in `~/.local/bin/` if installed for a user) works.

Thank you for the fix. It worked for me. I have the line in my ~/.bashrc file, but it doesn't seem to work there. I have to add it to my ~/.local/bin/winapps The only problem is that the "fix" of adding the file to ~/.local/bin/winapps is that the fix is lost on upgrade.
