### ISSUE TITLE
Next Steps

### ISSUE THREAD

**Issue by LDprg** [winapps-org/winapps#2]
So now we have created the repo. However what are the plans? 
On the original [Winapps Issue](https://github.com/Fmstrat/winapps/issues/269) there were some open questions.

Here are some of them:
- Reuse Code or Rewrite (or both)?
- If rewrite which language?
- How about the Issues and PRs on the original repo?
- Maybe changing the Logo?

**Comment by LDprg** [comment]
I also think that the install progress could be simplified (

**Comment by freechelmi** [comment]
I would say : 
- migrate the current main branch with history on our new develop branch
- Select 10 or 20 relevant issue to import manually , and suggest the other to open on new trackers if needed
- Ask people to resubmit their PR here after we tag the 0.1 and the test their PR on it ?
- Or as you say start over in Rust or something else

**Comment by oskardotglobal** [comment]
Some people were talking about replacing freerdp which is something we might consider for a rewrite

**Comment by LDprg** [comment]
> I would say : 
> - migrate the current main branch with history on our new develop branch
> - Select 10 or 20 relevant issue to import manually , and suggest the other to open on new trackers if needed
> - Ask people to resubmit their PR here after we tag the 0.1 and the test their PR on it ?
> - Or as you say start over in Rust or something else 

What if we do this and after we get a stable result start rewriting the software on another branch. This way we would solve the multiple fork issue. The only downside is that we would have to maintain 2 different codebases for some time.

**Comment by freechelmi** [comment]
Yes That is what I would do : 

- Deliver a 0.1 shell on master based with all good contributions on forks and PR from 2021 on
- Then Start another branch with some breaking changes

**Comment by oskardotglobal** [comment]
> * Select 10 or 20 relevant issue to import manually , and suggest the other to open on new trackers if needed

We could probably automate this if needed to pull all issues and filter out some

> * Or as you say start over in Rust or something else

I'm not that familiar with rust but we might want to look into not just using the rust [freerdp2 bindings](https://lib.rs/crates/freerdp2) but something like [IronRDP](https://github.com/Devolutions/IronRDP) or [rdp-rs](https://github.com/citronneur/rdp-rs). We could also take a step away from rdp and look into whatever [Rustdesk](https://github.com/rustdesk/rustdesk) uses internally

**Comment by oskardotglobal** [comment]
But lets maybe move this to #4
