### ISSUE TITLE
RDPWindows is not running: blah blah blah

### ISSUE THREAD

**Issue by Ellish-idk** [winapps-org/winapps#200]
so, when i type "bin/winapps check" it says the thing in the title.

when i type "virsh start RDPWindows" i get the following:
```
error: error when getting domain info «RDPWindows»
```
(that's a rough translation)

virsh list gives me nothing
also, did i mention that it sees my vm only when i type the commands with "sudo"?
(update: it sees my vm if i type virsh --connect qemu:///system list --all, even without "sudo", but that's just one command, as far as im aware)

i wouldn't make this issue if this didn't happen:
```
yapopug@asus-fx705gm-debian:~/winapps$ sudo bin/winapps check
You need to create a ~/.config/winapps/winapps.conf configuration. Exiting...
```
Here's my configuration file that is called "winapps.conf", and is at in ~/.config/winapps:
```
RDP_USER="yaroslav"
RDP_PASS="2468"
#RDP_DOMAIN="MYDOMAIN"
#RDP_IP="192.168.123.111"
#RDP_SCALE=100
#RDP_FLAGS=""
#MULTIMON="true"
#DEBUG="true"
```
I clearly see that my config file exists, it has the required name, and it is in the folder it wants it to be in. I don't see a single problem that stops me from getting started on winapps. Just in case you'll ask: i set it (the file) up manualy.

**Comment by oskardotglobal** [comment]
Did you follow the installation guide?

**Comment by oskardotglobal** [comment]
@kernelghost We should find a way to set that `qemu:///system` env var (I forget what it's called) automatically or document that it should be set

**Comment by Ellish-idk** [comment]
> Did you follow the installation guide?

yes, i did, i don't know what i was supposed to follow to prevent this

**Comment by Ellish-idk** [comment]
I figured it out: so basically, since i used sudo to detect my vm, it runs the command as root user, so what I did is making a config file in the same directory, but for the root user, and it works! Wow, i'm so dumb.

**Comment by Ellish-idk** [comment]
I figured it out: so basically, since i used sudo to detect my vm, it runs the command as root user, so what I did is making a config file in the same directory, but for the root user, and it works! Wow, i'm so dumb.
