### ISSUE TITLE
Apps don't run from shortcuts

### ISSUE THREAD

**Issue by Ellish-idk** [winapps-org/winapps#202]
Apps don't run from shortcuts
Apps don't run from shortcuts
Apps don't run from shortcuts
Apps don't run from shortcuts
Apps don't run from shortcuts
Apps don't run from shortcuts
Apps don't run from shortcuts
Apps don't run from shortcuts
Apps don't run from shortcuts
Apps don't run from shortcuts
Apps don't run from shortcuts
what do i else say
ok, nothing happens when i click on an app shortcut

**Comment by LDprg** [comment]
@Ellish-idk The setup includes a command for testing freerdp. Please run it and post the logs with the behaviour.

You know issues with "does not work" are not very helpful without any information or logs, etc!

**Comment by Ellish-idk** [comment]
> @Ellish-idk The setup includes a command for testing freerdp. Please run it and post the logs with the behaviour.
> 
> You know issues with "does not work" are not very helpful without any information or logs, etc!

Where i'm supposed to get the logs from
