### ISSUE TITLE
Use without local vm

### ISSUE THREAD

**Issue by io-mneese** [winapps-org/winapps#203]
At $company we can use a pre-existing virtual machine for different apps.

Is it possible to use the installer script without a local Windows installation and instead use the remote rdp server?

**Comment by oskardotglobal** [comment]
It should be, just skip the VM installation guide and set the config parameters like the IP, user and password to your actual login for the other machine.

**Comment by io-mneese** [comment]
That does not work because the installer requires that the variable WAFLAVOR is either docker, podman or libvirt:

https://github.com/winapps-org/winapps/blob/ed88ae911148ac7129e01f6eaad488928e3b2a14/installer.sh#L1487

**Comment by fbartels** [comment]
The code already has `libvirt` as a possible third option, seems the installer also needs a "manual" option to allow users to specify a remote ip in `RDP_IP`

https://github.com/winapps-org/winapps/blob/ed88ae911148ac7129e01f6eaad488928e3b2a14/installer.sh#L1487-L1510

Its been a while since I last ran this project on my system and must say that the process looks really nice.

**Comment by oskardotglobal** [comment]
> Its been a while since I last ran this project on my system and must say that the progress looks really nice.

Yeah, courtesy of @KernelGhost, he cleaned up the codebase a lot

**Comment by KernelGhost** [comment]
This can certainly be achieved, however we would need to implement a new WAFLAVOR named 'remote' (or something to that effect) to allow WinApps to attempt a connection to a user-specified IP address without conducting additional dependency checks, user group membership checks or virtual machine status checks. The automatic pause feature should also be disabled when this 'remote' backend is selected. This isn't implemented yet, but could be with relatively little effort.

**Comment by oskardotglobal** [comment]
@KernelGhost See #204

**Comment by LDprg** [comment]
closing in favour of #204

**Comment by KernelGhost** [comment]
Oops I missed that. Awesome work!
