### ISSUE TITLE
MULTIMON=true makes the window non-interactible.

### ISSUE THREAD

**Issue by kyngs** [winapps-org/winapps#209]
If I set MULTIMON=true, I can no longer interact with the windows (click on them, resize them, etc.). Disabling the compositor does not work.
Please take a look at the attached vid. 
Is this a freerdp bug? 

https://github.com/user-attachments/assets/bf762907-eea8-43f6-bb9c-542a2bb53060

**Comment by oskardotglobal** [comment]
Yup, this is a bug with freerdp that is well-known. Just disable the flag.

**Comment by kyngs** [comment]
> Yup, this is a bug with freerdp that is well-known. Just disable the flag.

Is there a freerdp issue tracking this? 
without multimon, winapps behaves pretty silly, so it is kinda unfortunate to use it

**Comment by oskardotglobal** [comment]
There should be, best you check on their issue tracker

**Comment by kyngs** [comment]
> There should be, best you check on their issue tracker

I honestly can't find the issue on their bugtracker; you said this is a known issue?

**Comment by joezhouchenye** [comment]
Same issue. However, I found out that this option is not necessarily an option for multiple monitors, unlike the freerdp 2 version. I can move the window around multiple monitors even using MULTIMON=false. Only the maximized window will be forced to one of the monitors.
