### ISSUE TITLE
Saving dialogs crashes

### ISSUE THREAD

**Issue by ToOest** [winapps-org/winapps#21]
As soon as I try to open the saving dialogue in any MS office program it is nonresponsive. I also cannot click the original window anymore. Are there any fixes? The problem occurs on manjaro Linux gnome, on my old laptop with manjaro xfce it works though.

**Comment by ToOest** [comment]
I use wayland.

Am Mi., 19. Juli 2023 um 22:01 Uhr schrieb LDprg ***@***.***>:

**Comment by LDprg** [comment]
Wayland is fully supported by now, as we currently us xfreerdp only and don't select between wlfreerdp. 

You can fix the problem by:
* Using X11 until we added Wayland support (This is related to #19 )
* Replacing all xfreerdp with wlfreerdp in the script your self (in theory, not tested)

Also if you change the script to automatically select between wlfreerdp and xfreerdp feel free to contribute.

**Comment by LDprg** [comment]
@ToOest 
Does it work as expected when using X11? Just so that I can change the label of the issue.

**Comment by ToOest** [comment]
No, if I just change xfreerdp for wlfreerdp in the script and run it the VM launches in a window, logs in and then closes, with the script failing. DId not do any further troubleshooting.

**Comment by LDprg** [comment]
Sorry, this is related to wlfreerdp to have no support for streaming apps directly. Currently there's no way to get freerdp to work stable on Wayland in the way winapps needs it to (we still need to investigate into this).

For now the only way to get winapps working stable is to switch to X11. 

@ToOest However I want to verify this is a wayland problem, so if possible boot into a x11 and check if the problem persists.
