### ISSUE TITLE
Add Support for Homebrew (NetCat)

### ISSUE THREAD

**Issue by dannymate** [winapps-org/winapps#211]
So I'm using Bazzite (KDE), I'm currently writing up a guide on setting it up with Podman. I am using Homebrew to install CLI packages (podman-compose, dialog, netcat).

I got through the installer.sh and the apps installed fine but they didn't launch from the application menu, I was getting "Port 3389 is closed". They did however launch from the terminal. I pinpointed it to the WinApps file (line 487): https://github.com/winapps-org/winapps/blob/fa5f058e5ae85cc6d876848d2f08449de2e0383f/bin/winapps#L487C1-L487C85

I realised that the `nc` command wasn't picking up the `netcat` package I'd installed via Brew. Ideally I want to avoid layering a package if possible. I did a bit of research and added `eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"` to the top just underneath the bash deceleration. `/home/linuxbrew/.linuxbrew/bin/brew` (it's already in $PATH Edit: The directory up to "bin" is in path not directly pointing to brew) is the default brew install location on linux for reference. 

By including this line Homebrew can act as a distro agnostic/atomic friendly package install option. I'm unsure if this is the **best** way of doing it but is this something you'd consider a pull request for? 

Also, and I can create another issue if necessary but, when I run `winapps check` it says "Application not found". It's not getting in the way but I thought I'd bring it up just in case.

**Comment by oskardotglobal** [comment]
Since you're writing a guide, make sure to mention to install FreeRDP3, not FreeRDP2. This is also the cause of the error you're facing. 

As for the issue with the location of netcat, loading the brew shellenv inside the winapps script is definitely not the best solution. Where is the `nc` binary located on PATH for you? Did you try manually adding that line to your `.bashrc` (even if you're using another shell)?

**Comment by dannymate** [comment]
Here's the guide I wrote: https://universal-blue.discourse.group/t/winapps-in-bazzite-portal/2199/3

In regards to the first point with the error I actually think that winapps thinks I'm passing in an application. Considering the command isn't mentioned in the guides anymore, maybe it's been gotten rid of? To be clear everything is functional and someone in the Bazzite discord has gotten it working (with bugs) on Cosmic DE.

I have `/home/linuxbrew/.linuxbrew/bin/` on PATH. This is configured for you on Bazzite and it allows packages installed from brew to be run as you would expect. e.g. `nc -Z blah blah`. My nc is `/home/linuxbrew/.linuxbrew/bin/nc`. 

Getting people to configure the `.bashrc` is too much work and besides that if we went the route of using the [freerdp brew package](https://formulae.brew.sh/formula/freerdp#default) then I'd have to add that into .bashrc too. I can mess around with it if you need me to test something though.

Hmm... in fact I wonder if because I've installed podman-compose via brew that's why that other person is having issues with their windows container not booting when launching a windows app on startup. (Because I still have that line in my WinApps)

The solution I think would be best is one that doesn't require extra configuration to work with brew packages from the end user side. I don't know what the best solution is but in my opinion tucking that configuration WinApps side would be better. I can do some research and see how others handle it and get back to you if you think that'll be useful.

**Comment by dannymate** [comment]
Yeah I'm fairly sure we should be sorting this Bazzite-side so I'm going to close this but feel free to message if you need to. Thanks for your help and patience. :)

For others, just in case, adding `eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"` to your ~/.bashrc or ~/.bash_profile and restarting should sort you out.
