### ISSUE TITLE
Visual bug, login screen square shows up

### ISSUE THREAD

**Issue by coffandro** [winapps-org/winapps#254]
![image](https://github.com/user-attachments/assets/c9c94457-a82b-4e72-9f64-e45d0c074d5f)
This shows up in the upper left corner of my desktop whenever I run adobe Illustrator.
Similar things happen whenever a new screen shows up in other applications but they then transform into whatever they actually are (Like a dialog and such).

I'm on a thinkpad p50 running fedora 40 with podman as a backend

**Comment by oskardotglobal** [comment]
This is a freerdp issue.

**Comment by coffandro** [comment]
I don't think so, it literally just happens when I open Adobe illustrator.
Another issue that has arrisen that is even odder btw, when I open an app like word or illustrator it won't appear until I open another app so to open illustrator I first have to open explorer.exe and then illustrator.

**Comment by oskardotglobal** [comment]
I do not care what you think. This is an issue with FreeRDP.
Regarding your other problem, please open another issue since it is unrelated.

**Comment by coffandro** [comment]
Jeeze louise, alright

**Comment by oskardotglobal** [comment]
Doesn't mean you can't keep this open

**Comment by entitybtw** [comment]
same problem

**Comment by entitybtw** [comment]
> same problem, i using gentoo

happens when opening Adobe after effects

**Comment by entitybtw** [comment]
help pls

**Comment by entitybtw** [comment]
tried downgrading to 3.4.0-r12, the number of glitches has decreased significantly

**Comment by entitybtw** [comment]
@coffandro  what desktop environment are u using?

**Comment by coffandro** [comment]
I was using Gnome 46

**Comment by entitybtw** [comment]
> I was using Gnome 46

oh, idk, i use hyprland

**Comment by entitybtw** [comment]
any update?

**Comment by entitybtw** [comment]
> Dude, repeatedly asking for updates don't speed it up, wait and hope that it get's fixed or go try to do it yourself.

I tried almost everything possible, nothing helps

**Comment by oskardotglobal** [comment]
Closing since this is an issue we cannot directly fix
