### ISSUE TITLE
Can't install winapps using setup bash script in installation pages

### ISSUE THREAD

**Issue by alosslessdev** [winapps-org/winapps#256]
Hi, so i followed the steps in this page: https://github.com/winapps-org/winapps/blob/main/docs/docker.md 
to make a windows virtual machine using docker engine, and it worked, so Then i stopped the docker container and tried to run this command: 
bash <(curl https://raw.githubusercontent.com/winapps-org/winapps/main/setup.sh)
in that page and it didn't work saying i hadn't created the winapps config file so i created it, then i ran that bash script again and it seemed to work, there i chose to install, then install system wide, then install apps automatically but it exited saying i hadn't installed some dependencies, so i ran  
sudo dnf install dialog first, then i ran 
sudo dnf install -y dialog freerdp iproute libnotify nmap-ncat, 
and when i run the setup bash script again it says:
/dev/fd/63: line 208: ./install/inquirer.sh: No such file or directory
and indeed it doesn't exist in my machine when i run ls /dev/fd/, i am running Fedora 40, i always ran the setup bash script in the winapps folder used in this page: https://github.com/winapps-org/winapps/blob/main/docs/docker.md   

i have tried to run docker compose --file ./compose.yaml down
docker compose --file ~/.config/winapps/compose.yaml up on the winapps directory described in  https://github.com/winapps-org/winapps/blob/main/docs/docker.md  but this didn't solve the problem. i have also tried to run the setup script with the windows vm running, on the winapps directory but it didn't work either. i have also tried to reboot my machine after installing the dependencies and trying again. i hope uninstalling everything and then reinstalling is not the only solution.

all docker commands had to be run with sudo to get around permission issues. i'm guessing this happens because i installed docker desktop first before installing docker engine and then i  uninstalled docker desktop and docker engine and then i only installed docker engine

**Comment by Juanfi8** [comment]
Hi, I'm using ubuntu 24.04 and I ran into the same problem.  The solution was to "sudo rm -r .local/bin/winapps-src/" and to run the bash script again (you have to this every time the script fails or you re install). For the docker issue, don't use sudo (root) because it will search in the root home directory for the config file. Instead, add the user to the docker group.

**Comment by alosslessdev** [comment]
In fedora the local directory is at /usr/local/bin

**Comment by freechelmi** [comment]
Yes this part in docker doc was misleading , it's fixed in https://github.com/winapps-org/winapps/pull/264
