### ISSUE TITLE
Windows automatically minimizing when switching workspaces

### ISSUE THREAD

**Issue by Juanfi8** [winapps-org/winapps#257]
Hi, i correctly installed the project and everything is working as expected. Nevertheless, windows apps are minimizing automatically every time I switch workspaces in my host linux machine. I think it is related to the docker/freerdp config, but I don't have any experience with these.
Do you have any idea on how to resolve this issue?

Distro: Ubuntu 24.04 LTS
De: Gnome

**Comment by oskardotglobal** [comment]
This is an upstream freerdp issue. You could try enabling multimon in the winapps config and see if that helps.

**Comment by itiligent** [comment]
This took me a while to get my had around, but I've found a reasonalby happy medium on Debian. 
When opening a winapp, right click the winapp's panel icon to either maximize or restore it, then move the app to the workspace you want, now left click the panel app icon again TWICE... This action seems to trigger the full screen correctly and also works on a triple monitor setup too.  If all your screens are set to the same scale and resolution then FreeRDP seems a little less finicky. 
The Multimon setting did not work for me, in fact it broke te above workaround.

**Comment by Juanfi8** [comment]
Thanks for the recommendation. I found a working solution from the FreeRDP git repository. The problem was solved in version 3.7.0 of FreeRDP. Version 3.5.1 that I was using (the one available from APT) still had the bug. I installed the flatpak version, and it started working. However, the bug was solved for Xorg, but it is still persistent in Wayland for me.

**Comment by oskardotglobal** [comment]
If you're facing issues with your distro's provided FreeRDP, it is recommended that you try building from source; the flatpak version has it's own issues

**Comment by Juanfi8** [comment]
After several testing, I came to a solution using the flatpak version. The Flatpak version (3.8.0) of FreeRDP fixed the minimizing problem but needs the $desktopSession (environment variable)  set to gnome. In Ubuntu, it is set to Ubuntu by default. By setting the variable to gnome in the winapps executable, apps stopped minimizing.

**Comment by Juanfi8** [comment]
After several testing, I came to a solution using the flatpak version. The Flatpak version (3.8.0) of FreeRDP fixed the minimizing problem but needs the $desktopSession (environment variable)  set to gnome. In Ubuntu, it is set to Ubuntu by default. By setting the variable to gnome in the winapps executable, apps stopped minimizing.
