### ISSUE TITLE
exit code 14 after upgrading to fedora41 beta

### ISSUE THREAD

**Issue by DaRandomCube** [winapps-org/winapps#265]
what happened is, simply upgrading to f41 beta and boom, cannot connect via rdp anymore
the issues with the same error didn't tell the fix
winapps flavor: podman
here is the log:
```
[21:16:39:348] [43332:0000a945] [ERROR][com.freerdp.core.transport] - [transport_default_write]: BIO_should_retry returned a system error 32: Broken pipe
[21:16:39:348] [43332:0000a945] [ERROR][com.freerdp.core] - [transport_default_write]: ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x0002000D]
[21:16:36:913] [43332:0000a945] [INFO][com.freerdp.client.x11] - [xf_setup_x11]: Enabling X11 debug mode.
```

**Comment by DaRandomCube** [comment]
i tried pinging the vm ip address, no output

**Comment by friday06** [comment]
this is common among the winapps flavors, i tried the workaround mentioned in other error 14 topic, none of them worked for me. 
try doing the /cert:ignore in flags of winapps conf

**Comment by DaRandomCube** [comment]
> this is common among the winapps flavors, i tried the workaround mentioned in other error 14 topic, none of them worked for me. try doing the /cert:ignore in flags of winapps conf

tried it, doesn't work

**Comment by friday06** [comment]
![windowsiscringe](https://github.com/user-attachments/assets/ee8cb5a0-c4e2-485c-a07e-2c2df1d47ad0)
try turning that off & run the script again ?

**Comment by DaRandomCube** [comment]
already off :(
![image](https://github.com/user-attachments/assets/f543bca0-f72e-45ae-911c-4c948b8004b1)

**Comment by DaRandomCube** [comment]
here is the fun thing
![image](https://github.com/user-attachments/assets/41fb1c20-869a-42c3-9c28-01c509b3ade2)
when you try to connect using setup script, there should be something in `~/.config/freerdp/server/`
however, it's empty

**Comment by DaRandomCube** [comment]
Hello?

**Comment by DaRandomCube** [comment]
guess i found a solution, not recommended to do it, but that what worked for me
remove the installed firewall and reboot

**Comment by DaRandomCube** [comment]
soo, it returned again, even without a firewall
i noticed something when trying to stop the container, it outputs
```
internal:0:0-0: Error: Could not process rule: No such file or directory
```
searching give me nothing helpful

**Comment by DaRandomCube** [comment]
update, now it works after reinstalling firewalld and adding ports
```
firewall-cmd --zone=trusted --add-port=3389/udp

firewall-cmd --zone=trusted --add-port=3389/tcp
```
plus, adding missing tables in `nft`
```
sudo nft add table inet firewalld
```
cannot guarantee that the problem won't happen again, will leave open for a while

**Comment by ccbadd** [comment]
> update, now it works after reinstalling firewalld and adding ports
> 
> ```
> firewall-cmd --zone=trusted --add-port=3389/udp
> 
> firewall-cmd --zone=trusted --add-port=3389/tcp
> ```
> 
> plus, adding missing tables in `nft`
> 
> ```
> sudo nft add table inet firewalld
> ```
> 
> cannot guarantee that the problem won't happen again, will leave open for a while

I just tried this with Fedora 40 KDE and still get the error.

**Comment by DaRandomCube** [comment]
for now i should able to login normally by setting the above rules to be permanent
```
firewall-cmd --runtime-to-permanent
```

___
> > update, now it works after reinstalling firewalld and adding ports
> > ```
> > firewall-cmd --zone=trusted --add-port=3389/udp
> > 
> > firewall-cmd --zone=trusted --add-port=3389/tcp
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > plus, adding missing tables in `nft`
> > ```
> > sudo nft add table inet firewalld
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > cannot guarantee that the problem won't happen again, will leave open for a while
> 
> I logged into the web interface and added a password to default user, "Docker", and the error goes away. Now I just get a blank screen.

did you put the password also in winapps.conf?

**Comment by ccbadd** [comment]
> did you put the password also in winapps.conf?
Yes I did.  The step needed to open the web link and set the username/password really should be added to the howto.

**Comment by ccbadd** [comment]
I did get it working.  In the config file I had to set "MULTIMON=true" and docker-compose up after and it works fine now.  I do have a 3 monitor setup.

**Comment by DaRandomCube** [comment]
> I did get it working. In the config file I had to set "MULTIMON=true" and docker-compose up after and it works fine now. I do have a 3 monitor setup.

Well thats the cause
Multimon is know for resulting in black screen

**Comment by ccbadd** [comment]
> Well thats the cause Multimon is know for resulting in black screen

I did read that but I took it that having it set to false would be what caused the black screen.

**Comment by DaRandomCube** [comment]
huh
anyway will close the issue, since your issue is different, open a different issue
