### ISSUE TITLE
Office 2024 apps are not detected.

### ISSUE THREAD

**Issue by tr1ckydev** [winapps-org/winapps#274]
Office 2021 apps are detected as normal, but recently I tried Office 2024 using deployment tool (just Excel and Word) but they aren't detected by winapps.

**Comment by tr1ckydev** [comment]
Seems like manual path is the way for now.
Excel 2024: `winapps manual "C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE"`
Word 2024: `winapps manual "C:\Program Files\Microsoft Office\root\Office16\WINWORD.EXE"`

**Comment by gordoncheong** [comment]
That's strange. I used the online installer to get Office 2024 and they can be detected normally. They should have been on the same install path anyway so I don't really see why it wouldn't work?
![image](https://github.com/user-attachments/assets/aad75d4a-0d9d-4db9-befa-605b3b3a517b)

**Comment by tr1ckydev** [comment]
Oh sorry, you're right. It was just my KDE bugging out.
