### ISSUE TITLE
Does anyone have freerdp3-x11.deb for PopOS?

### ISSUE THREAD

**Issue by alchemistake** [winapps-org/winapps#285]
How can install freerdp3 on my PopOS installation? Jenkins links are broken or the server is down. I tried to add ubuntu repos for a sec, install freerdp3 then remove the apt repo. It didn't work (no wonder.)

How can i install it? I think i can manually download it for debian or ubuntu but im not sure whether that would work or not.

I spent 45 minutes now. Im not a linux beginner but i never had this problem before. if someone can point me to correct place it would be awesome.

(i tried to build from source but dependencies package is not defined on popos apt as well so i rage quited after 30-45 minutes of fiddling.)

(don't type "just use flatpak", i have a personal hatred against appimage, flatpak and snap. discrimination agains package managers are still legal.)

**Comment by MrTumnis** [comment]
[http://ftp.de.debian.org/debian/pool/main/f/freerdp3/libfreerdp3-3_3.6.3+dfsg1-2+b1_amd64.deb](url)
