### ISSUE TITLE
exiting with status 11

### ISSUE THREAD

**Issue by Eaglerider70** [winapps-org/winapps#288]
Every time I try to install WinApps on my Arch Linux, it exits with status 11 (container not running; windows is not running), which it is running. I set up Docker perfectly. Is it something to do with the Docker container being inside my browser? Do I have to set up a Docker container in my terminal? If I have to, please help me.

Quick note, yes windows is also running inside docker.

**Comment by Eaglerider70** [comment]
I need help with creating the proper docker container for winapps btw

**Comment by obscure1980** [comment]
How did you fix this?
my windows container is running but i get always:

Installing WinApps.
Checking for existing conflicting WinApps installations... Done!
Attempting to load WinApps configuration file... Done!
Checking whether dependencies are installed... Done!
Checking container status... Failed!

ERROR: CONTAINER NOT RUNNING.
Windows is not running.
--------------------------------------------------------------------------------
Please ensure Windows is powered on:
docker compose --file ~/.config/winapps/compose.yaml start

if i check wit docker ps evertinig is fine

**Comment by Eaglerider70** [comment]
I never fixed it I just gave up and just used wine instead and also I dont want windows crapware running on my system

**Comment by obscure1980** [comment]
thx for answering me.
i got it to work ... if you are still interested at some point, I will be happy to help you

**Comment by sciencehope** [comment]
Hello @obscure1980 , could you explain how did you fix this please? I am having the same issue. I already tried with virtual-manager then switch to docker but still having same issue.
