### ISSUE TITLE
Windows 7 support

### ISSUE THREAD

**Issue by albert-wayen** [winapps-org/winapps#29]
How can i use windows7 iso instead of windows 10 thank you

**Comment by LDprg** [comment]
Yes you can, although you need to setup you VM manually not via quickemu (as recommended). Generally you can use every windows that runs in a vm and is supported by freerdp. Enabling RDP might be different, but it should work. 

However I would recommend only using winapps with windows 10 and 11. Setup the vm with quickemu and enable RDP and add the registries entries.  The process is much faster and you can run windows 7 apps on windows 10 too.

**Comment by albert-wayen** [comment]
thank you brother i realy appreciate your support , have a nice day
