### ISSUE TITLE
setup.sh: line 208: ./install/inquirer.sh: No such file or directory - Exiting with status '1'.

### ISSUE THREAD

**Issue by neobladerunner** [winapps-org/winapps#298]
Hopefully is just something simple but Step 4 in which I run the winapps setup fails with the error in title. I never am able to actually reach the winapps setup screen. Using Mint w/ latest Kernel if that matters.

**Comment by CalpDev** [comment]
Same error. I found a temporary workaround.

Steps:
1. Install inquirer.sh and setup.sh from repo.
2. Open setup.sh file.
3. Redirect Inquirer env line to local inquirer.sh file.
4. Run setup.sh file we just changed.

**Comment by oskardotglobal** [comment]
Is `/tmp` writable?

**Comment by CalpDev** [comment]
> Is `/tmp` writable?

Yes, it also has waInquirer.sh file in it.

`user@computer:~$ ls -ld /tmp
drwxrwxrwt 30 root root 4096 Oct 16 19:37 /tmp`

**Comment by neobladerunner** [comment]
> Have you installed WinApps before?

Yes, I had an installation fail initially because I didn't have my winapps docker running. I started it, went to run the installer again, and started having this problem.

**Comment by neobladerunner** [comment]
I got the installer to progress past the error by copying the install/inquirer.sh from this project into a "install" subfolder within the winapps folder I'm installing winapps in. I'm now getting a new error which may or may not be related (I suspect this was the main issue in the first place).

`Checking container status... Cannot connect to the Docker daemon at unix:///home/username/.docker/desktop/docker.sock. Is the docker daemon running?`

I can access my windows docker installation fine through the browser, so I have no idea why winapps isn't seeing it.

**Comment by ilbebino08** [comment]
same error here
I tried to do @CalpDev work around and it doesn't work now i have error code 11
`WinApps installation already present at /home/ilbebino/.local/bin/winapps-src. Updating...
Già aggiornato.
Installing WinApps.
Checking for existing conflicting WinApps installations... Done!
Attempting to load WinApps configuration file... Done!
Checking whether dependencies are installed... Done!
Checking container status... Failed!

ERROR: CONTAINER NOT RUNNING.
Windows is not running.
--------------------------------------------------------------------------------
Please ensure Windows is powered on:
podman-compose --file ~/.config/winapps/compose.yaml start
--------------------------------------------------------------------------------
Exiting with status '11'.
`

when I run the command it gives me:
`CRITICAL:podman_compose:missing files: ['/home/ilbebino/.config/winapps/compose.yaml']`

**Comment by oskardotglobal** [comment]
you were supposed to create the file during setup

**Comment by ilbebino08** [comment]
> you were supposed to create the file during setup

You're right, I didn't realize it was THAT file, I think it was deleted either by me by mistake while trying to fix it or when the installation failed

**Comment by ilbebino08** [comment]
> you were supposed to create the file during setup

I realized that instead it's not that file, the one that needs to be created during setup, but winapps.conf, what I'm missing is compose.yaml

**Comment by OWL4C** [comment]
It would be great if the installer could account for this and fix this error when it occurs, either manually download ./install or uninstall winapps, then reinstall. (Since the entire installer doesn't start you can't uninstall either)

**Comment by ilbebino08** [comment]
> (Since the entire installer doesn't start you can't uninstall either)

U can make it start by downloading inquirer.sh and editing the setup.sh with the path of inquirer.sh

**Comment by neobladerunner** [comment]
> > (Since the entire installer doesn't start you can't uninstall either)
> 
> U can make it start by downloading inquirer.sh and editing the setup.sh with the path of inquirer.sh

Not really ideal though - forcing users to manually create a directory and download/copy a file from the repo versus the app just being able to figure out what file it needs after a failed first attempt seems fairly logical.

**Comment by BobbieERay** [comment]
> > > (Since the entire installer doesn't start you can't uninstall either)
> > 
> > 
> > U can make it start by downloading inquirer.sh and editing the setup.sh with the path of inquirer.sh
> 
> Not really ideal though - forcing users to manually create a directory and download/copy a file from the repo versus the app just being able to figure out what file it needs after a failed first attempt seems fairly logical.

I agree. As 9/10 users will run into this problem during the install, because either the docker engine wasn't running, or their user wasn't added to the docker group, the install documentation should either be updated to make the pre-conditions very clear, or the installer should handle a failed install.

**Comment by Arodd2000** [comment]
Instead of manually downloading inquirer.sh and changing the path, is there a directory we can clear so setup.sh starts "fresh" and tries to create inquirer.sh?

**Comment by yongweiy** [comment]
A workaround that works me is to remove the previous install via `rm -rf ~/.local/bin/winapps-src`.

**Comment by ilolm** [comment]
You have to change directory to ```~/.local/bin/winapps-src``` , and execute ```./setup.sh``` again.

That worked for me.

**Comment by oskardotglobal** [comment]
Closing this in favour of #350
