### ISSUE TITLE
File Not Found Error When Running Winapps on NixOS

### ISSUE THREAD

**Issue by Seeker0472** [winapps-org/winapps#300]
## Description:

I attempted to install the winapps project on NixOS using the feat-nix-packaging branch with home-manager. However, I encountered issues when trying to run installed programs. The process fails with the following error messages: 
```
~/.local/bin ❯ bash word-o365 
word-o365: line 2: /home/seeker/.local/bin/winapps: No such file or directory
```

I had to fix this by creating an symbolic link:

```

~/.local/bin ❯ which winapps
/etc/profiles/per-user/seeker/bin/winapps

~/.local/bin ❯ ln -s /etc/profiles/per-user/seeker/bin/winapps winapps

```

And the content of the file

```
~/.local/bin ❯ cat word-o365 
#!/usr/bin/env bash
/home/seeker/.local/bin/winapps word-o365
```

## Steps to Reproduce:

    Run winapps Install -> Current User ->Manual (Default)  -> Set up all detected officially supported applications -> Set up all detected applications ->
    cd into ~/.local/bin
    run any program

## Expected Behavior:
The program should start succesfully

## Actual Behavior:
The program fails due to File not found error

## System Information:

    OS: NixOS 24.11.20241014.a3c0b3b (Vicuna) x86_64 
    DE: none+dwm 
    WM: dwm
    Branch: feat-nix-packaging

**Comment by oskardotglobal** [comment]
This might be a home-manager thing since normally it's supposed to replace that `~/.local/bin` path with the path to the nix store at build time

**Comment by Seeker0472** [comment]
> This might be a home-manager thing since normally it's supposed to replace that `~/.local/bin` path with the path to the nix store at build time

Yes,I think so, and adding `home.file.".local/bin/winapps".source = "${winapps}/bin/winapps";`to [my dotfiles](https://github.com/Seeker0472/nixos/blob/develop/modules/gui/winapps.nix)  sloves this problem.
