### ISSUE TITLE
ERROR: WINDOWS NONEXISTENT. EXITING.

### ISSUE THREAD

**Issue by bonzoskill** [winapps-org/winapps#301]
Hi, after installing without error on arch, the icons of the application installed appears on arch launcher but when trying to open this error occurs : ERROR: WINDOWS NONEXISTENT. EXITING.

In the file `~/.local/share/winapps/winapps.log`, the log is : 

[Fri Oct 18 01:11:11 AM CEST 2024-13497] START
[Fri Oct 18 01:11:11 AM CEST 2024-13497] SCRIPT_DIR: /home/bonzo/.local/bin
[Fri Oct 18 01:11:11 AM CEST 2024-13497] SCRIPT_ARGS: word-o365
[Fri Oct 18 01:11:11 AM CEST 2024-13497] HOME_DIR: /home/bonzo
[Fri Oct 18 01:11:11 AM CEST 2024-13497] LAST_RUN: 1729008905
[Fri Oct 18 01:11:11 AM CEST 2024-13497] THIS_RUN: 1729206671
[Fri Oct 18 01:11:11 AM CEST 2024-13497] Using FreeRDP command 'xfreerdp3'.
[Fri Oct 18 01:11:11 AM CEST 2024-13497] ERROR: WINDOWS NONEXISTENT. EXITING.

**Comment by KernelGhost** [comment]
@bonzoskill Thanks for reporting this issue. To help us investigate further, could you provide additional details? You can start by adding `set -x` at the beginning of the `winapps` script for initial debugging. Additionally, could you let us know which backend you're using for WinApps, as well as your Linux distribution and desktop environment? Any additional debugging information would be greatly appreciated. Thank you!

**Comment by bonzoskill** [comment]
@KernelGhost Thanks for the reply. I'm using **libvirt** as backend, **Arch** as  distribution, **Wayland** as DE and **ZSH** as Shell. 
I followed the guide for the VM with libvirt and everything  worked well.
I've git cloned the winapps repo and executed `./setup.sh` for the install wizard. If using `bash <(curl https://raw.githubusercontent.com/winapps-org/winapps/main/setup.sh)` , it gives me this error :

% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 79583  100 79583    0     0   296k      0 --:--:-- --:--:-- --:--:--  295k
################################################################################
#                                                                              #
#                            WinApps Install Wizard                            #
#                                                                              #
################################################################################

/proc/self/fd/13: line 208: ./install/inquirer.sh: No such file or directory
Exiting with status '1'.

Anyway if i git clone and run `./setup.sh` i can install the apps i want and them appears on Arch launcher. When i try to lunch them this error occurs. (I tried to install for the User and System either but same error)

if i run `set -x ./winapps > output.txt 2>&1` the output is `zsh: permission denied: ./winapps`
if i run `set -x ./winapps/setup.sh > output.txt 2>&1` the output is 

[1m################################################################################
#                                                                              #
#                            WinApps Install Wizard                            #
#                                                                              #
################################################################################
[0m
./winapps/setup.sh: line 208: ./install/inquirer.sh: No such file or directory
[1;41;37mExiting with status '1'.[0m


I think is not exactly what you asked for but tell me if i should call winapps's application in another way. Thanks

**Comment by oskardotglobal** [comment]
This was fixed in the commit closing #310
