### ISSUE TITLE
Different winapps programs are merging in one icon on apps panel

### ISSUE THREAD

**Issue by Damglador** [winapps-org/winapps#302]
Maybe that's just a quirk of the program or Wayland, but in demonstrations, each programmed opened by WinApps is shown as a separate app on a bottom panel. For me, every time I launch a new program with WinApps, all WinApps windows close and open again, and they always count as one program on the bottom bar + window naming is getting messed up.

![зображення](https://github.com/user-attachments/assets/99c2d94c-2c36-49c2-972e-2606d9cd6af6)

DE: Plasma 6.1.5 to 6.2.1 (the issue persisted)
Distro: Arch
Display Manger: Wayland

**Comment by Damglador** [comment]
As a manual workaround, it's possible to manually assign .desktop file to a window using Plasma tools. Open apps one by one and create rules that bind window with title, for example, "Microsoft Visual Studio" to .desktop file of this program.

**Comment by oskardotglobal** [comment]
Closing this in favour of #267 as it describes the same problem

**Comment by otaolafranc** [comment]
> As a manual workaround, it's possible to manually assign .desktop file to a window using Plasma tools. Open apps one by one and create rules that bind window with title, for example, "Microsoft Visual Studio" to .desktop file of this program.
> 
> ![зображення](https://github.com/user-attachments/assets/88b7841a-fb21-49f0-a2e0-2112307e6348)

hello,
I am using plasma and when i open an app, such as word for example, i dont have a windows decoration (bar on the top) so, not sure how one can acces to the menu to associate it with a .desktop file, could you please give a brief but more step by step guide for this? I would love to have my different windows apps separated. thanks

**Comment by Damglador** [comment]
@otaolafranc Alt+F3 when the desired window is in focus.
