### ISSUE TITLE
All windows disappearing randomly

### ISSUE THREAD

**Issue by chris-fogel-intermetro-net** [winapps-org/winapps#307]
I've been using WinApps for some time now (in Mint 21.3 Cinnamon). Whenever I open a new application (excel, notepad, etc), all WinApps windows disappear and then once the new application starts, they all re-appear. Not a big issue, but randomly, all the windows just disappear. The only way to get them back to the screen is to start a new application (I usually just run 'cmd'). Is there something that will prevent them from randomly disappearing?

**Comment by calculatetech** [comment]
I'm noticing this as well on Fedora 40 KDE.

**Comment by jokocc** [comment]
I have the same problem with Fedora 40 Gnome-Wayland

**Comment by oskardotglobal** [comment]
We cannot fix this as it is a FreeRDP issue.

**Comment by chris-fogel-intermetro-net** [comment]
For those following this thread, I opened a case with freerdp..

https://github.com/FreeRDP/FreeRDP/issues/10928

**Comment by chris-fogel-intermetro-net** [comment]
askardotglobal, are you able to help me with this "request" so I can get the information to the guys over at freerdp?

"You will most likely need to create some identification for the session (user/server/...) and in case there is another instance running with that exact same connection parameters pass the application to start to that instance and let that instance send it to the server.

the hard part here is most likely to properly identify the sessions are identical, so some research is necessary there."

**Comment by chris-fogel-intermetro-net** [comment]
For those still following, I am not sure if you are using multiple monitors or not, but I am, and what I have done is modify the **winapps** script to limit my window size to the first monitor hard coded and not let is span. It doesn't allow me to move the windows around to other monitors, but, I haven't had the random windows disappearing issue so far since I've done that.

Hope this helps someone.

**Comment by jokocc** [comment]
> For those still following, I am not sure if you are using multiple monitors or not, but I am, and what I have done is modify the **winapps** script to limit my window size to the first monitor hard coded and not let it span. It doesn't allow me to move the windows around to other monitors, but, I haven't had the random windows disappearing issue so far since I've done that.
> 
> Hope this helps someone.

I do use multiple monitor. Can you give me specific instruction on how to "modify the winapps" script?
thx.

**Comment by chris-fogel-intermetro-net** [comment]
jokocc, 

For me, it installed the winapps script in ~/.local/bin/winapps, so this is the one I edited. Look for the "function waRunCommand()". It should have four(4) blocks that look like the below:

```
        $FREERDP_COMMAND \
            /d:"$RDP_DOMAIN" \
            /u:"$RDP_USER" \
            /p:"$RDP_PASS" \
            /scale:"$RDP_SCALE" \                <------------- Modified
            +dynamic-resolution \                <------------- Removed
            +auto-reconnect \
            +home-drive \
            /audio-mode:1 \
            /wm-class:"Microsoft Windows" \
            /t:"Windows RDP Session [$RDP_IP]" \
            /v:"$RDP_IP" &>/dev/null &
```

I set the scale (because that wasn't setting for me for some reason) to a manual 140 (but you can leave alone if the font it large enough for you). I also removed the dynamic-resolution and added my hard coded settings. I did this to all four entries just in case, because I noticed that running a manual once for instance would revert all settings if i ran a manual program after running a pre-installed one.

My new blocks look more like this:
```
        $FREERDP_COMMAND \
            /d:"$RDP_DOMAIN" \
            /u:"$RDP_USER" \
            /p:"$RDP_PASS" \
            /scale:"140" \                              <--------- Modified
            /window-position:"100x40" \                 <--------- Added
            /smart-sizing:"3840x2160" \                 <--------- Added
            /w:"3840" \                                 <--------- Added
            /h:"2160" \                                 <--------- Added
            +auto-reconnect \
            +home-drive \
            /audio-mode:1 \
            /wm-class:"Microsoft Windows" \
            /t:"Windows RDP Session [$RDP_IP]" \
            /v:"$RDP_IP" &>/dev/null &
```

Obviously my monitor size is 3840x2160, just match to your native size of yours. Like stated earlier, this will hard code your "windows" machine to be in the leftmost monitor, but it does seem to be more stable.

Chris

**Comment by jokocc** [comment]
@chris-fogel-intermetro-net 
Appreciated your reply very much. Thanks.
I will try the use (and modify as needed). I'll write back after further testing.

**Comment by jokocc** [comment]
have tried the code and still failed. On top of that the upgrade to fedora 41 broke functionality.
in the end I decided to use direct qemu virtualization for the time being. until winapps and supporting library is more stable
