### ISSUE TITLE
Pre-commit has CLA not signed

### ISSUE THREAD

**Issue by LDprg** [winapps-org/winapps#31]
@oskardotglobal  Seems like pre-commit doesn't want to sign our cla. 
Is there a way to fix this, because the cla check fails (see here #30).

**Comment by LDprg** [comment]
This would be a solution: https://github.com/cla-assistant/cla-assistant/issues/173

**Comment by oskardotglobal** [comment]
I just added the bot as ignored and clicked "recheck". It will now be exempt from CLAs. Closing this
