### ISSUE TITLE
Only small set of default application detected

### ISSUE THREAD

**Issue by RiccardoBarbieri** [winapps-org/winapps#315]
When trying to install winapps, in the selection menu for detected default applications only the following list is displayed:

![image](https://github.com/user-attachments/assets/8a9fc360-f5ea-4e68-a48e-d6937ff8e86b)

Should I manually put the exe files for the apps I want to install at the locations specified in the info files under winapps/apps or am I missing something?

**Comment by oskardotglobal** [comment]
In case this is just a misunderstanding:
- You can scroll the list using the arrow keys
- We do not install the app for you, you have to manually install the app from within the VM and then re-run the setup

**Comment by RiccardoBarbieri** [comment]
It's the second case for me, thank you!
