### ISSUE TITLE
visual bug, login screen square shows up (again)

### ISSUE THREAD

**Issue by entitybtw** [winapps-org/winapps#327]
https://github.com/winapps-org/winapps/issues/254
same problem, using gentoo linux with a hyprland, help please.-.
happens when opening Adobe After Effects (any version)

**Comment by entitybtw** [comment]
![image](https://github.com/user-attachments/assets/ee998676-3d7b-42c6-aed0-aaeb8d19965d)

**Comment by oskardotglobal** [comment]
Duplicate

**Comment by entitybtw** [comment]
=(
