### ISSUE TITLE
Window border line

### ISSUE THREAD

**Issue by Damglador** [winapps-org/winapps#328]
![Знімок 2024 11 14 20:56:05](https://github.com/user-attachments/assets/a89ae4ed-b15d-4485-9c93-e2710a8a45b1)
Some windows have this weird border that is always on top, even if the window is unfocused. In example its Microsoft SQL Server Management Studio 20, but I think I've seen it happen with other apps as well

**Comment by oskardotglobal** [comment]
This is a FreeRDP bug we cannot fix.

**Comment by Damglador** [comment]
Sadge
