### ISSUE TITLE
winapps check doesn't execute properly, and gets stuck

### ISSUE THREAD

**Issue by Ilya-JBR** [winapps-org/winapps#33]
I enabled remote desktop in Windows added the register, changed windows name to RDPWindows ,cloned the latest winapps from github.

Running on:
kde-plasma 5.27.7
kernel-version  6.4.6-1-default (64-bit)
xfreerdp version 2.10.0 (2.10.0)
on wayland (it doens't matter, it doesn't work on x11 neither)(I wish you added a wayland option)

My environment variables:
[text.txt](https://github.com/winapps-org/winapps/files/12266933/text.txt)

Command output:
[text.txt](https://github.com/winapps-org/winapps/files/12266883/text.txt)

then nothing happens and If i terminate it and if run `./installer.sh` i get:
[text.txt](https://github.com/winapps-org/winapps/files/12266926/text.txt)

**Comment by LDprg** [comment]
It seems like your config is incorrect. 
Have configured winapps with the config file (see documentation)?

You can try to ping the windows vm and set the ip manually. Also check if the user and password is correct. 

When running sudo /bin/winapps check you should get a file explorer if the connection works.

**Comment by svta-7125** [comment]
For me it's just saying: 

RDPWindows is not running, run:
  virsh start RDPWindows
