### ISSUE TITLE
Terminate container when closing

### ISSUE THREAD

**Issue by Boyfinn** [winapps-org/winapps#332]
I'm trying to get the windows container to terminate when closing an application in order to free resources from the virtual machine.
Running `docker ps` reveals that the windows container still persists after closing the application.

**Comment by oskardotglobal** [comment]
This exists. Turn on Autopause in the config.

**Comment by Boyfinn** [comment]
> This exists. Turn on Autopause in the config.

The config has a comment above this parameter saying that:
`This is currently INCOMPATIBLE with 'docker' and 'manual'.`

**Comment by oskardotglobal** [comment]
Yes, because Docker struggles pausing the container. You could try using Podman instead.

**Comment by Boyfinn** [comment]
> Yes, because Docker struggles pausing the container. You could try using Podman instead.

I know this isn't really on topic with the issue, but is there a separate compose file for setting up winapps with podman that isn't mentioned in the documentation? There is almost immediately docker specific stuff in the template compose file provided by the docker/podman installation page which doesn't work when trying to compose with podman.
