### ISSUE TITLE
Podman compose unresolved alias

### ISSUE THREAD

**Issue by Boyfinn** [winapps-org/winapps#337]
I'm attempting to move from a docker setup over to podman. However, running the podman composer command:
`podman-compose --file ./compose.yaml up
Using the provided template `compose.yaml`-file produces the error(s):
```
Error: short-name "dockurr/windows" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
[windows] | Error: no container with name or ID "WinApps" found: no such container
```
If there is a separate composer template for podman, the I haven't found one in the official tutorial/documentation, or even [unofficial tutorials](https://gist.github.com/eylenburg/38e5da371b7fedc0662198efc66be57b#option-1-running-any-office-version-including-365-with-winapps)

System info:
OS: Linux Mint 22 x86_64
Kernel: 6.8.0-49-generic
DE: Cinnamon 6.2.9

**Comment by oskardotglobal** [comment]
Did you try adding Docker Hub as the default registry or changing the image to docker.io/dockurr/windows

**Comment by Boyfinn** [comment]
> Did you try adding Docker Hub as the default registry or changing the image to docker.io/dockurr/windows

Could you please elaborate? I don't see this anywhere in the docs or the comments laid out in the .yaml file?

**Comment by GrandUpheaval** [comment]
I was having the same issue, change in the compose.yaml `image: dockurr/windows` to `image: docker.io/dockurr/windows`

**Comment by Boyfinn** [comment]
> I was having the same issue, change in the compose.yaml `image: dockurr/windows` to `image: docker.io/dockurr/windows`

Could someone please update the docs with this information? Or at least add the correct link in the commented part of that line in the .yaml?
