### ISSUE TITLE
Docker: wmic baseboard returns « No Instance(s) Available. »

### ISSUE THREAD

**Issue by Teskann** [winapps-org/winapps#338]
Hi there,

I setup WinApps a few days ago with Docker, this is great tool. Unfortunately some softwares could not work in WinApps.
Indeed, some need to access specific hardware information for activation and copy protection.
The thing is, if you run `wmic baseboard` in a powershell, you get « No Instance(s) Available ».

![image](https://github.com/user-attachments/assets/364635e4-1f36-434b-8908-fb43e0dbc452)

I think this is preventing software activation to work properly in some cases.
Does any Docker expert know a way to run the VM so that it can access the baseboard information ? I truly believe it could improve the number of supported softwares.

Thanks,

**Comment by oskardotglobal** [comment]
In this case, it should easier for you to use a libvirt VM

**Comment by Teskann** [comment]
Hi @oskardotglobal thank you for your reply. Indeed, I managed to do it with libvirt, adding similar information to the xml file of the configuration of the VM:

```xml
<domain>
  <os>
    ...
    <smbios mode='sysinfo'/>
  </os>
  ...
  <sysinfo type='smbios'>
    <system>
      <entry name='manufacturer'>Your Manufacturer</entry>
      <entry name='product'>Your Product Name</entry>
      <entry name='version'>1.0</entry>
      <entry name='serial'>12345ABCDE</entry>
    </system>
    <baseBoard>
      <entry name='manufacturer'>Your Board Manufacturer</entry>
      <entry name='product'>Your Board Product Name</entry>
      <entry name='version'>1.0</entry>
      <entry name='serial'>BoardSerial12345</entry>
    </baseBoard>
  </sysinfo>
</domain>
```

The software that I couldn't use with docker works with these settings !
