### ISSUE TITLE
Missing install/RDPApps.reg

### ISSUE THREAD

**Issue by alvaroggc** [winapps-org/winapps#355]
The instructions say that we need to merge `install/RDPApps.reg` into the Windows Registry manually, but that file is missing inside the repository. 

What I finally did was to use the same file from the [old WinApps repository](https://github.com/Fmstrat/winapps/tree/main/install), but I don't know if there is any risks using that one, like compatibility issues.

**Comment by oskardotglobal** [comment]
Where exactly does it say that? It's supposed to say oem, not install.
For now, grab the files from the oem folder.

**Comment by alvaroggc** [comment]
At the end of **Step 1: Configure a Windows VM** (under Installation) it says:

> If you already have a Windows VM or server you wish to use with WinApps, you will need to merge `install/RDPApps.reg` into the Windows Registry manually.

Now everything is clear :) 

Should I close this issue myself now or after the documentation is fixed?

**Comment by oskardotglobal** [comment]
I've fixed that in #312.
