### ISSUE TITLE
Define LIBVIRT_DEFAULT_URI during installation.

### ISSUE THREAD

**Issue by SVTA-OP** [winapps-org/winapps#362]
the system was unable to find my windows 10 virtual machine until i added this env variable in the beginning of the command `setup.sh` or by manually adding it in the script where the virsh commands are run to check the state of the vms.

https://github.com/user-attachments/assets/a790673c-35f2-4893-8981-43d31950cec0

Ignore the Error 14 as the script does find apps half the time but i won't be able to open them since the script doesnt know where to look for the VM.  
  
I am using a VM installed in libvirt on fedora 41 with GNOME 47.

Please let me know for more details.

**Comment by SVTA-OP** [comment]
Update: I was able to get some apps working when running the binaries with the path

For example: `LIBVIRT_DEFAULT_URI=qemu:///system ./mspaint`

https://github.com/user-attachments/assets/263311ac-1bde-46ee-91ef-4d154b640f29  

Will adding the above line in the '.bashrc' or '.zshrc' fix this problem as this appears to be a problem with the path finding on my end?

**Comment by oskardotglobal** [comment]
Please read the documentation. It is mentioned at the top of the Libvirt installation guide.

**Comment by SVTA-OP** [comment]
Yes, found out about issue #310 and one of the workarounds fixed the issue, thanks.
