### ISSUE TITLE
Ability to run app with GPU with NVIDIA-Prime

### ISSUE THREAD

**Issue by brownhr** [winapps-org/winapps#366]
When running the application with 
```sh
prime-run winapps manual C:\path\to\app.exe
```
I still see a spike in the integrated GPU usage, rather than the dedicated. Prime-run works well on other applications, so I suspect the FreeRDP is not running correctly with prime.

Logging into the NoVNC server for the windows Docker container apparently uses the GPU, as it runs through Chromium, which I have configured to do so.

Ultimately, I'm not an expert in prime, FreeRDP, or anything like that. If the question I'm asking isn't even relevant, I understand. Just curious if others have been able to get any GPU working with something like Prime. Performance is not absolutely vital.

Happy to provide other information if needed.

**Comment by oskardotglobal** [comment]
Maybe try setting your freerdp command to `prime-run <path to freerdp>` in the winapps.conf?

**Comment by brownhr** [comment]
Ah, that makes sense! I was able to successfully connect to the docker container _manually_ by calling `prime-run xfreerdp /u:... /p:... etc.`. Performance is actually quite reasonable.

However, in trying to do that, I'm getting exit status '5' with the install script, as it seems to be unable to parse the input once I add `prime-run` to the `FREERDP_COMMAND` line, like so:

```sh
FREERDP_COMMAND="prime-run xfreerdp3"

# Also doesn't work
FREERDP_COMMAND="/bin/prime-run /bin/xfreerdp3"

# I also tried `alias prime-xfreerdp3="prime-run xfreerdp3"` to no avail:
FREERDP_COMMAND="prime-xfreerdp3"
```

Specifying the path to xfreerdp3 with
```sh
FREERDP_COMMAND="/bin/xfreerdp3"
```

For reference, this is the error from the script. Again, I do have all the requirements; I believe the install script may not be properly parsing the `FREERDP_COMMAND`:

```sh
Installing WinApps.
Checking for existing conflicting WinApps installations... Done!
Attempting to load WinApps configuration file... Done!
Checking whether dependencies are installed... Failed!

ERROR: MISSING DEPENDENCIES.
Please install 'FreeRDP' version 3 to proceed.
--------------------------------------------------------------------------------
Debian/Ubuntu-based systems:
  sudo apt install freerdp3-x11
Red Hat/Fedora-based systems:
  sudo dnf install freerdp
Arch Linux systems:
  sudo pacman -S freerdp
Gentoo Linux systems:
  sudo emerge --ask net-misc/freerdp

You can also install FreeRDP as a Flatpak.
Install Flatpak, add the Flathub repository and then install FreeRDP:
flatpak install flathub com.freerdp.FreeRDP
sudo flatpak override --filesystem=home com.freerdp.FreeRDP
--------------------------------------------------------------------------------
Exiting with status '5'.
```

---

However, even with the manual setup, the Windows container is still rendering _internally_ with the CPU; prime only changes how the RDP session is drawn on the host. So I don't think this is the solution I'm looking for, even though performance does seem to be a good bit better. I'll experiment with GPU passthrough on a libvirt/QEMU setup and post if I find anything.

Thanks for the help!
