### ISSUE TITLE
Support for forwarding Linux and macOS guests to host

### ISSUE THREAD

**Issue by upintheairsheep** [winapps-org/winapps#37]
winapps will soon support macOS, but solutions to forward X11 on Linux via X11 itself and waypipe, and macOS via WayPipe and XQuartz respectively, and the support for macOS should include macOS 10.4 to macOS 13, because macOS drops compatibility for older architextures, frameworks, etc and therefor demand is higher.

**Comment by upintheairsheep** [comment]
Both Linux and macOS forwarding for Parallels required you to have a special tools package installed, but I think diversifying is a good thing. A single machine that can run Windows, macOS, Linux, and Android apps in the same setting without any virtual machine lock-in is just amazing.

**Comment by oskardotglobal** [comment]
This is related to #35.
