### ISSUE TITLE
[Suggestion/Request] Onedrive

### ISSUE THREAD

**Issue by paulo-roger** [winapps-org/winapps#39]
Would it be possible to access Onedrive the way we do with Excel?

Even if it would sync only inside the VM.

**Comment by oskardotglobal** [comment]
What do you mean? Accessing onedrive on linux?

**Comment by Atem18** [comment]
Hi @oskardotglobal, is it possible to reopen it ? It would be great to have the OneDrive files accessible from Linux itself just like it is possible on Windows.

**Comment by oskardotglobal** [comment]
Sorry, that's beyond the scope of this project
