### ISSUE TITLE
Does Magix Vegas Pro 20 function?

### ISSUE THREAD

**Issue by amakuramio** [winapps-org/winapps#40]
I am sorry for disturbing. I can't live without Vegas Pro and have already tried Olive, Davinci, Kdenlive.

Bottles supports Steam version of 18, which is very old and only allows one window open at a time.

Does Winapps support Magix Vegas Pro?

**Comment by oskardotglobal** [comment]
In theory, every app is supported, however, you'd probably want GPU passthrough, so Steam is probably your best bet. Have you tried installing it natively and running Vegas via Proton?

**Comment by amakuramio** [comment]
> In theory, every app is supported, however, you'd probably want GPU passthrough, so Steam is probably your best bet. Have you tried installing it natively and running Vegas via Proton?

Thank you for your reply, I will try your suggestions then report.

**Comment by amakuramio** [comment]
Magix Vegas Pro 21 (trial) works, a bit slow, but that is my own error, but it works. Great. Now I can finally use Linux. Closed.
