### ISSUE TITLE
Extreme lagging with MS Word

### ISSUE THREAD

**Issue by Dimacat-exe** [winapps-org/winapps#45]
Im trying hard to use MS Word but its just too lag. In VM it had no problem. Anyway to fĩx?

**Comment by Dimacat-exe** [comment]
Im using Office 2019 and excel and pp seems fine. But word is so so lagging and stuck. Anyway to fix it?

**Comment by Dimacat-exe** [comment]
Specs is 6 cpu and 10gb ram

**Comment by oskardotglobal** [comment]
Also, what version of freerdp are you running? And what distro are you on?

**Comment by Dimacat-exe** [comment]
![Screenshot_20230926_220532](https://github.com/winapps-org/winapps/assets/141384815/4ff1d2e5-eafc-41e4-a5e0-6ffd09240013)
Here is the look. It was very glitchy when i try to move the cursor to the MS Word ribbon. And also when i press close it appear a message ask me to share. There was something very wrong

**Comment by Dimacat-exe** [comment]
freerdp2-x11 (2.10.0+dfsg1-1)
Maybe this?

**Comment by LDprg** [comment]
Are you running X11 or Wayland? Wayland is currently not supported. Another thing could be that your that you didnt load the reg file in your vm (Take a look at the vm setup guide). This is needed because you might miss some compressions for rdp.

**Comment by Dimacat-exe** [comment]
Im running x11 and yes, im also load the reg. Dont know really why it got so lagging...

**Comment by Dimacat-exe** [comment]
Any fix? I guess it is rdp problem or something...

**Comment by Dimacat-exe** [comment]
Fixed. I changed to gnome and it work like a charm. Maybe Kubuntu and KDE has something wrong with their stuff?
