### ISSUE TITLE
Update documentation for Windows 11

### ISSUE THREAD

**Issue by eylenburg** [winapps-org/winapps#53]
The documentation only explains how to set up a Windows 10 VM. As Windows 10 will only be supported until 2025, it would be useful - but not urgent - to update the documentation for Windows 11. It's probably mostly the same except for setting up the virtual TPM.

**Comment by oskardotglobal** [comment]
Or actually there already is, but win10 is still the default

**Comment by LDprg** [comment]
> The documentation is outdated. The first version of the rewrite will be out soon, where we use quickemu. There will be an option to run win11 too.

@oskardotglobal we should consider a option for the rewrite

**Comment by oskardotglobal** [comment]
Easily possible with #94.

**Comment by LDprg** [comment]
@oskardotglobal true, we could easily support tiny10 tiny11 win11 and win10.

I would draw the line of official support at win10 and tiny10. Windows versions below 10 would be unofficial stuff.

**Comment by freechelmi** [comment]
This is fixed in Current master
