### ISSUE TITLE
UWP Apps are not Detected by installer.sh

### ISSUE THREAD

**Issue by Hyperspeed1313** [winapps-org/winapps#59]
In my specific use case, the missing program is iTunes which was installed from the Microsoft Store. The installer didn't detect it and so I couldn't add it.

For now I can use the legacy installer as an alternate, but I expect at some point Apple will deprecate the non-store version of iTunes.

**Comment by KernelGhost** [comment]
It may be useful to review https://github.com/Fmstrat/winapps/pull/129 and port modifications as appropriate.

**Comment by oskardotglobal** [comment]
Closing this in favour of #183 since that contains more detail.
