### ISSUE TITLE
Clarify that an IP address is required if not using QEMU

### ISSUE THREAD

**Issue by Hyperspeed1313** [winapps-org/winapps#60]
I'd much rather run Windows on my dedicated Proxmox server than using up resources on my primary gaming PC, which as I understand it, should be possible as winapps is basically a wrapper on freerdp to make it easier to set up. But with my config file set up, running `winapps check` or `installer.sh` stall immediately because I'm not a member of `libvirt` or `kvm` groups. I have no desire to virtualize using my desktop's resources, so I don't think I would need libvirt/kvm installed, but I don't know how to get the rest of the setup finished without it.

**Comment by Hyperspeed1313** [comment]
Figured it out... once I specified the static IP address in the config file it stopped asking for those groups.

**Comment by Hyperspeed1313** [comment]
Actually, since this is something that works and people should be aware exists, I've reopened this issue until the documentation provides instructions for remote Windows systems.

**Comment by oskardotglobal** [comment]
Thank you for your contribution.
