### ISSUE TITLE
Can't open anything

### ISSUE THREAD

**Issue by mak448a** [winapps-org/winapps#69]
I can't open anything. When I run the install script, a cmd window pops up, and everything seems to be going fine.
But afterwards, when I run `winapps explorer` (which is what the shortcuts run) it pops up with the error
```
You need to run 'install.sh' first.
```
But I already ran it. So what's going on?

**Comment by mak448a** [comment]
Ok I uninstalled and reinstalled and now it's just not outputting anything.

**Comment by LDprg** [comment]
@mak448a Did you follow the setup docs? 
Also please share your system details (Wayland/X11, Distro).

**Comment by mak448a** [comment]
Wayland, Fedora 39 KDE spin. Main branch.

**Comment by oskardotglobal** [comment]
Wayland is currently unsupported.

**Comment by kgadberry** [comment]
> Wayland is currently unsupported.

I'm using Fedora Silverblue 39 and it works fine using wayland when doing `./bin/winapps check`, but running the installed `.local/bin/winapps` shows the same error as OP.

**Comment by eylenburg** [comment]
> Wayland is currently unsupported.

Is there any workaround with xwayland?

**Comment by mak448a** [comment]
> > Wayland is currently unsupported.
> 
> Is there any workaround with xwayland?

Not any that I'm aware of, but try using cassowary instead of winapps, which has Wayland support.

**Comment by bogdan-calapod** [comment]
Is cassowary still under development though ?

**Comment by eylenburg** [comment]
> Is cassowary still under development though ?

No I don't think so :(
