### ISSUE TITLE
How to integrate existing VirtualBox Windows 10 guest?

### ISSUE THREAD

**Issue by shmu26** [winapps-org/winapps#73]
Can I use my existing VB guest on winapps?
If so, how?
Also, any tips for using winapps on a KDE Plasma host?

**Comment by oskardotglobal** [comment]
Yes, just follow the last steps in the installation guide after the VM is created: https://github.com/winapps-org/winapps/blob/main/docs/KVM.md

Then, set RDP_IP in winapps.conf to the IP of your virtual machine
Beware though, Virtualbox is *very slow* compared to KVM / QEMU
