### ISSUE TITLE
RDP_SCALE does not function with most settings

### ISSUE THREAD

**Issue by Contruffin** [winapps-org/winapps#77]
Using Linux Mint 21.3 on a Microsoft Surface Book 2 (Intel i7-8650U, Nvidia GTX1060).

I just set up winapps yesterday, but I'm noticing that the RDP_SCALE option in winapps.conf does not function with most of the settings mentioned in the setup instructions. When set to an invalid number, the programs simply fail to open. I also cannot open the full Windows VM through RDP. It seems to work when set to 100 and 140, although it does not work with 120, 160, and 180.

**Comment by oskardotglobal** [comment]
This is a bug in freerdp. Have you tried using a nightly version?

**Comment by LDprg** [comment]
This is most likely a freerdp issue.

**Comment by KernelGhost** [comment]
We encountered a similar problem in #145. AFAIK, this has now been fixed in #144. @eylenburg @Contruffin Can you please confirm if this is the case?

**Comment by eylenburg** [comment]
Yes, works fine with RDP_SCALE=150 now
