### ISSUE TITLE
Winapps does not work for FreeRDP3

### ISSUE THREAD

**Issue by s-kesh** [winapps-org/winapps#81]
Thanks for this wonderful script. But the script does not work with freeRDP3.

"./bin/winapps windows" works with both freeRDP3 and freeRDP2. But "./bin/winapps check" does not work with freeRDP3.

freeRDP version: 3.4.0

**Comment by GreatNovaDragon** [comment]
at least under arch linux, the command for freeRDP2 is xfreerdp3 and not xfreerdp, which is porbably why it doesnt work, cause it checks for xfreerdp

**Comment by LDprg** [comment]
@s-kesh The patch hs been merged, can you verify that it fixed your problem?

**Comment by s-kesh** [comment]
Sorry for such a late reply. Now it works.
