### ISSUE TITLE
Virsh session vs. system (Apps silently fails to start)

### ISSUE THREAD

**Issue by peppergrayxyz** [winapps-org/winapps#83]
Hello,

there seems to be different ways of running kvm/qemu/libvirt which lead to the VM running either in system or session pool. It is hard to grasp these concepts and harder to configure everything so that it works.

If the VM "RDPWindows" is running in the system pool, the script will fail.

**Observed behavior**
"RDPWindows is not running, run:  virsh start RDPWindows" (from shell)
App fails silently to start from menu

**Excpected behavour**
App is starting

**Proposal**
use ```virsh --connect qemu:///system list``` or ```virsh --connect qemu:///session list``` explicitly (winapps:57)
(same for net-dhcp-leases default, (winapps:62))

**Comment by caleskog** [comment]
I have the same problem. The check command fails because the VM is not found.

**Comment by npmanos** [comment]
Add `export LIBVIRT_DEFAULT_URI=qemu:///system` to your shell profile (.bashrc, .zshrc, etc.) and then reboot.

**Comment by oskardotglobal** [comment]
We are currently working on running the VM inside Docker, see #94, which should solve most of these issues.
Closing this since it seems resolved.
