### ISSUE TITLE
Latest FreeRDP Dependency Behavior and Documentation

### ISSUE THREAD

**Issue by Ahmedsaed** [winapps-org/winapps#91]
**Describe the bug**
The behavior of the FreeRDP dependency differs from user expectations due to the discrepancy between the version packaged in certain Linux distributions and the version marked as latest by the developer. Updating the documentation or providing a warning within the application may help guide users encountering this issue.

**Steps to Reproduce**:
1. Install FreeRDP from the repository of a Linux distribution that packages the latest released version (e.g., version 3.4.0).
1. Attempt to use FreeRDP with the `/app` argument.
1. Observe FreeRDP printing the help message and exiting unexpectedly.

**Expected Behavior**:
FreeRDP should properly handle the `/app` argument and perform the intended operation without issues.

**Actual Behavior**:
In the latest couple of released versions of FreeRDP (e.g., version 3.4.0), using the `/app` argument causes FreeRDP to print the help message and exit instead of executing the desired operation.

**System information:**
- Linux Distribution: Fedora 40
- Version of FreeRDP: 3.4.0

**Impact**:
This issue affects users relying on FreeRDP distro packages, particularly those needing to use the /app argument.

**Workaround**:
- Compiling the correct version of FreeRDP
- Using Distrobox or similar solutions to run a Linux container that has the binaries for the correct version in the repositories.
    - Use `distrobox-export` to export the binary to host system. Ex: `distrobox-export --bin /usr/bin/xfreerdp ~/.local/bin`

**Comment by KernelGhost** [comment]
@Ahmedsaed Could you please confirm if this issue still persists? WinApps should now fully support FreeRDPv3 and also supports FreeRDP installed as a Flatpak for users on distributions that don't offer version 3 via the official package manager repositories. I am running FreeRDP 3.6.2 and have not encountered any issues with the `/app` flag.

**Comment by f8ith** [comment]
I can reproduce the issue. The issue happens because winapps loads the config (Adds the flags to $RDP_COMMAND) before scanning for the system's FreeRDP version, causing the $FREERDP_COMMAND to be fixed as xfreerdp which is the default.
On systems where the binary is named "xfreerdp3", the error occurs. 

Simply moving the waGetFreeRDPCommand before waLoadConfig fixes the issue.
