### ISSUE TITLE
Trying to execute /bin/winapps check

### ISSUE THREAD

**Issue by G4CHIM4STER** [winapps-org/winapps#93]
Hello. I'm trying to install your wonderful software, but I've encountered several extremely annoying problems. from the current ones are:
1. **bin/winapps check** cannot connect to my local VM, despite all this - connection via xfreerdp works correctly
2. I assume that the **installer.sh** does not work for the same reason.

Can you help me ? 

Fedora 40
Kernel 6.8.8

**Comment by LDprg** [comment]
Since xfreerdp works I would recommend setting the ip manually in the config.

**Comment by shadyalfred** [comment]
How? @LDprg

**Comment by LDprg** [comment]
@shadyalfred With the RDP_IP option of the winapps config file. Read the README for more information.

**Comment by trottdeaje** [comment]
**Fedora 40
Kernel 6.8.8
FreeRDP version 3.5.1**

Running bin/winapps check doesn't open explorer for me. I went ahead and tried to launch it manually with the below and that works:

`xfreerdp /u:rdp-windows /p:password /v:192.168.124.27`

![image](https://github.com/winapps-org/winapps/assets/32769513/ca07efa7-7a29-483e-8877-f16a8c925943)


But if I append /app:"explorer", it shows the FreeRDP help text, as if /app: is not valid?

`xfreerdp /u:rdp-windows /p:password /v:192.168.124.27 /app:"explorer"`

![image](https://github.com/winapps-org/winapps/assets/32769513/9b55fc8c-f9b3-44b3-967f-3b0b1cfba822)


My conf file at ~/.config/winapps

RDP_USER="rdp-windows"
RDP_PASS="password"
#RDP_DOMAIN="MYDOMAIN"
RDP_IP="192.168.124.27"
#RDP_SCALE=100
#RDP_FLAGS=""
#MULTIMON="true"
DEBUG="true"

Running virsh list shows my VM running
![image](https://github.com/winapps-org/winapps/assets/32769513/066ef48e-efc9-46dd-87c0-e66bd062edf9)

At a lost here.

**Comment by SakiiCode** [comment]
The correct command would be `xfreerdp /u:rdp-windows /p:password /v:192.168.124.27 /app:program:"explorer.exe"`

**Comment by oskardotglobal** [comment]
@trottdeaje @G4CHIM4STER Please try this again with #87 merged, just run a `git pull` inside the winapps directory

**Comment by oskardotglobal** [comment]
Perfect. Closing this as resolved.
