### ISSUE TITLE
Error  "You are not a member of the libvirt group"

### ISSUE THREAD

**Issue by c2b2pss** [winapps-org/winapps#95]
Running either "bin/winapps check" OR "./installer.sh" gives:

```
You are not a member of the libvirt group. Run the below then reboot.
  sudo usermod -a -G libvirt $(whoami)
  sudo usermod -a -G kvm $(whoami)
```
I have checked and I am part of libvrt group.  Adding myself again says, I am already part of group. I can confirm that this error is not part of libvirt since I can run virt-manager and access VM, and run windows just fine.

Run out of ideas........ :-(

**Comment by LDprg** [comment]
Can you check your groups again with the groups command? Also try to run a virsh command like virsh list -all.

Another helpful thing would be to know your distro.

**Comment by cgerardin** [comment]
Hello,
Same here, souds like a bug.

When I test manually the `groups | grep -v libvirt` command used by bin/winapps :
![image](https://github.com/winapps-org/winapps/assets/76680083/96a84119-96d4-41c2-ad5e-4387d6ddc60d)

**Comment by LDprg** [comment]
@cgerardin Thx for reporting.

@oskardotglobal We might need a small fix here. Seems like a small bug in the code refinements.

**Comment by oskardotglobal** [comment]
There might be a not missing here, I'll check

**Comment by LDprg** [comment]
I opened a pr #97 fixing this. Any testing is welcome.

**Comment by LDprg** [comment]
@roldengarm does your vm shows up when using `virsh list`? If not you may be running the vm as admin

**Comment by LDprg** [comment]
@roldengarm did you specify the ip in the config file? (it should be 127.0.0.1)

**Comment by LDprg** [comment]
@roldengarm can you send the whole winapps config file and docker compose? Also some system specs could help.
And maybe you could try connecting to the vm directly using xfreerdp.

Note: you could have downloaded the reg file with a browser directly in the vm.

**Comment by LDprg** [comment]
@roldengarm you are using freerdp2 uninstall it and install freerdp3

**Comment by LDprg** [comment]
@oskardotglobal we should add a check if freerdp 3 is installed.

**Comment by LDprg** [comment]
@roldengarm thats some bit outdated docs. There is a official freerdp 3 version release (see github releases version 3.5 I think). I would use your package manager search function. Many package managers ships a freerdp3-x11 or freerdp3 package.

Don't use nightly builds without a specific reason. Install the package from your package manager.
